{40}{160}Downloaded From www.AllSubs.org
{350}{446}...Ýngiliz finans sistemlerinin|çöküþte olduðuna dair haberi yalanladý.
{449}{529}Açýklamaya göre, Barings'in|baþarýsýzlýðý diðerlerine mal edilemez...
{533}{630}Bu olaydan da Singapur'daki|sahtekar bir tüccar sorumludur.
{633}{712}Toplam zararýn ise|800 milyon ile...
{715}{767}Bir Milyar Pound arasýnda|olduðu tahmin ediliyor.
{1346}{1446}Þuna bakar mýsýn.|Þuradakine bir baksana.
{1449}{1519}- Zencinin yanýndaki mi?|- Evet.
{1522}{1626}Çok yazýk.|Çok iyi gözüküyor.
{1628}{1697}Þans bu, ne yaparsýn|deðil mi dostum?
{1699}{1744}Sanýrým bir þeyler|deneyebilirim.
{1747}{1792}Hayýr, Steve.|Hayýr, bir þey yapma.
{1795}{1854}Sakýn yapma.|Steve. Steve!
{1928}{2001}Selam, tatlým.|Sana bir þey göstermek istiyorum.
{2101}{2146}Sen aklýný mý kaçýrdýn?
{2149}{2201}Seni küçük pislik.
{2204}{2295}- Hem de bu ufacýk þeyle.|- Kitabý kapaðýna göre yargýlama hayatým.
{2298}{2345}- Git yaþýtlarýnla gez. Gerzek.|- Sakin ol dostum.
{2348}{2412}- Sadece konuþmaya çalýþýyorum.|- Çek git yoksa fena olur!
{2415}{2483}- Buradan çýkmaný istiyorum. Hemen.|- Gerçekten üzgün, tamam mý?
{2486}{2541}Tamam gidecek.|Saygýsýzlýk etmek istemedi.
{2543}{2591}Rahatsýz etmek istemiyordu tamam mý?
{2594}{2639}Söyle ona þunu|derhal içeri soksun,
{2642}{2687}- Ne? Ne?|- Þimdi onu ellerimle koparacaðým...
{2690}{2761}- ve boðazýndan içeri sokacaðým!
{2764}{2818}Fermuarýný kapat seni hayvan.|Beni öldürecek misin sen?
{2860}{2946}Boþ ver. Buna deðmez.
{2950}{3007}Bir daha yaptý.|Gününü göstereceðim.
{3007}{3070}Tabii ki oðlum, aynen öyle.
{3255}{3324}Nick! Nick!
{3327}{3385}Ýyi misin? Nick!
{3796}{3870}Maggie Thatcher sayesinde|Watford'dan Londra'ya gelmiþ...
{3870}{3914}ve Barings gibi gösteriþli bir yerde...
{3917}{3973}çalýþmaya baþlamýþtým.
{4036}{4098}Eðer tanýmadýysanýz,|yerde yatan benim.
{4101}{4179}Nick Leeson.|Eminim beni duymuþsunuzdur.
{4317}{4377}Barings dünyadaki en|eski özel bankaydý.
{4380}{4465}1800'lü yýllarda ünlü Louisiana|alýmlarýyla uðraþmýþtý.
{4469}{4520}O zamandan beri de hizmet veriyor.
{4520}{4570}Müþterileri arasýnda|kraliçe de var.
{4682}{4729}Bense basit bir katiptim,
{4732}{4799}ama bu kýsa sürecekti,|öyle umuyordum.
{4802}{4851}Araba kazasý.
{4854}{4901}Kafamý koltuðun|arkasýna çarptým...
{4901}{4946}ve burnumu kýrdým.
{4946}{5035}Geri kalanlara bir þey olmadý|çünkü emniyet kemerleri takýlýydý.
{5038}{5096}Zavallýcýk.
{5099}{5172}Ve þimdi, Nick, Arkadaki ofisten|çýkmayý çok istediðini biliyorum...
{5175}{5246}pazarlama kýsmýný|istiyorsun deðil mi?
{5246}{5315}Ancak bu arada,|baþka bir þey çýktý.
{5318}{5377}Jakarta ofisinde|sorunlarýmýz var.
{5377}{5455}Oraya gidip|iþleri düzene sokacak birine ihtiyacýmýz var.
{5458}{5547}Ve düþündüm de|bu neden Nick Leeson olmasýn?
{5729}{5803}Endonezya Uzak Doðu'daki|en önemli ekonomilerden birine sahipti...
{5806}{5863}herkes oraya|gitmeye can atardý.
{5866}{5918}"Yükselen pazar,"|adýný takmýþlardý.
{5921}{5978}Ve Barings bunu ilk fark eden|firma olmuþtu.
{5981}{6047}Kazançlar büyük olacaktý,
{6051}{6110}tabii risk de bir o kadar fazlaydý.
{6114}{6195}Nakil senetler|bir milyon Pound deðerinde.
{6199}{6257}Nakit kadar iyi.
{6260}{6313}Bunlarý buradan alýp,|sonra dýþarý çýkabilir,
{6313}{6363}ve buradaki komik çocukla|bir anlaþmaya varabiliriz-
{6366}{6416}Müþteriler bunlara|para dökmek istemez.
{6419}{6506}Senetlerin miktarlarýnýn|esas anlaþmaya uymadýðýný söylerler.
{6509}{6576}Gerçek neden- Hisseler düþer,|ve artýk bunlarý istemezler.
{6579}{6628}Tam bir pislik.
{6631}{6687}Kesinlikle,|Yüzde yüz haklýsýn, Susi.
{6690}{6744}Bu tam bir|baþ belasý.
{6849}{6905}Pazar sabahý saat 10:00'da,
{6908}{6973}Fýrtýnanýn þiddeti saatte-
{6976}{7022}Sertifikalarý diðer bir deyiþle|alýcýlarý sýnýflandýrmak benim görevimdi...
{7026}{7081}Ödememek için|bir nedenleri kalmamalarý gerekmeliydi.
{7084}{7178}Ardýndan ise, Barings bu kahrolasýca|dengenin tam üzerine oturmalýydý.
{7181}{7233}Sýkýcý bir iþti,|ama bu iþte baþarýlý olursam,
{7236}{7301}devamýnýn geleceði de|çok açýktý.
{7304}{7366}Bütün sertifikalar|isimlerine göre sýralanmýþ durumda.
{7369}{7424}Bütün belgeleme iþlemleri bitti.|Artýk belli bir düzene kavuþtular.
{7427}{7494}Dolayýsýyla, sizden|tek isteðim...
{7497}{7543}bir çek.
{7893}{7941}Selam. Ben Lisa.
{8050}{8137}Ben de, Nick Leeson.|Yardýmcý olabilir miyim?
{8139}{8220}Barings düzenlemelerde yardým|etmem için beni gönderdi. Size söylenmedi mi?
{8223}{8321}Tabii ki. O kadar uzun zaman oldu ki|Artýk umudumu kesmiþtim.
{8321}{8417}Peki, þimdi bu yýðýný ne yapacaðýz?|Þenlik ateþi mi yakacaðýz?
{8567}{8660}Onlar için çalýþmaya baþlamadan önce|Barings adýný duymamýþtým bile.
{8664}{8714}"Watford'da bir Barings|parký vardýr." gibi bir þey deðil sonuçta.
{8717}{8798}Londra'da büyük bir kahraman oldun.|Güneþin senin sayende doðacaðýna inanýyorlar.
{8801}{8904}Gerçekten mi? Kendimi þu|Japon askerler gibi hissetmeye baþlamýþtým,
{8907}{8972}bilirsin 20 yýl sonra|bile savaþ alanýnda çýkamazlar.
{8975}{9025}Burasý nasýl bir yer?
{9027}{9076}Gece dýþarý çýkmanýn|iyi olmadýðýný duymuþtum.
{9079}{9128}Sakýn inanma.|Buranýn yerlileri harika insanlar.
{9131}{9208}Buranýn en iyi yaný o kokuþmuþ|sömürgecilik zihniyetinden uzak olmasý...
{9212}{9266}Dünyaya hükmetme|gibi bir hýrs yok burada.
{9269}{9325}Asya'nýn bu yanýný|seviyorum.
{9328}{9405}Yani herkes baþarabilir.|Hangis salak okulu bitirdiðin önemli deðil.
{9408}{9495}Jakarta'ya gideceðimi söylediklerinde|haritaya bakmak zorunda kalmýþtým.
{9527}{9574}Aslýna bakarsan,|ben de ayný þeyi yaptým.
{9616}{9676}Asýl olmak istediðim|þey pazarlama iþine girmek.
{9679}{9734}Bu iþten sonra hala|bu iþi bana vermezlerse býrakýrým.
{9737}{9828}- Bütün hayatým boyunca yazý iþlerine|bakmak istemiyorum. Hýrslýyýz yani?
{9831}{9889}- Bu kötü mü?|- Hayýr çok güzel.
{9892}{9976}Hayatýn içine girmek istiyorum|Zevk almak istiyorum. Beni yanlýþ anlama.
{9979}{10028}Sýký çalýþ, sert oyna.
{10032}{10078}Sanýrým|bu benim.
{10128}{10212}Ýyi geceler, Nick.|Çok eðlenceliydi.
{10216}{10276}Öyleydi,|deðil mi?
{10279}{10352}- Tamam, iyi geceler.|- Yarýn görüþürüz.
{10424}{10471}Lisa çok çekiciydi, tamam mý?
{10474}{10528}Ýlk bakýþta aþk.
{10531}{10599}Birlikte senetler|üzerinde daha kolay çalýþtýk.
{10602}{10689}Bir süre sonra|Barings'in çoðu kaybý yok olmuþtu,|ve eve gitme vakti de gelmiþti.
{10692}{10757}- Görüþürüz, Lisa.|- Hoþça kal.
{11326}{11403}Sanýrým Lisa'nýn prensiyle|karþýlaþtýðýný söylersem abartmýþ olmam.
{11406}{11483}- Evet evet.|- O zaman hep birlikte|onlara mutluluklar dileyelim...
{11486}{11539}Singapur'daki yeni|hayatlarýnda, Nick...
{11542}{11621}pazarlamanýn genel müdürlüðünü yaparken...
{11625}{11700}Bu ne demekse...|Etkilendim tabii, ama-
{11727}{11779}Ve ayrýca|Nick, olaðanüstü...
{11783}{11835}...bir hediye aldýn|ve eminim ki,
{11837}{11907}ona çok iyi bakacaksýn|mutlu edeceksin...
{11910}{11971}ve diðer bütün þeyler.
{11974}{12056}Eðer yapmazsan,|bacaklarýný kýrarým tamam mý?
{12100}{12208}- Yapar.|- Seni çok seviyorum, Lisa Leeson.
{12211}{12259}Ben de seni, Nick.
{12429}{12484}Jakarta'daki baþarým üzerine,
{12488}{12562}Singapur'da çok daha önemli,|bir pazarda görevlendirildim,
{12565}{12622}böylece pazarlama|tekniklerimi de geniþletebilecektim.
{12626}{12695}Kesinlikle|doðru yoldaydým.
{12954}{13001}- Burasý mutfak.|- Burasý senin bölümün, hayatým.
{13004}{13053}Ne zamandan beri?|Zevzek.
{13101}{13146}Ve yatak odasý.
{13529}{13592}- Ýhtiyacýnýz olursa,|ben ofisimde olacaðým.|- Tamam. Sað olun.
{13595}{13647}- Ýyi günler.|- Teþekkürler. Ýyi günler.
{13719}{13794}- Watford'dan sonra hiç fena deðil, deðil mi?
{13797}{13873}Þey, bence þu yataðý|bir kontrol etmeliyiz, koca oðlan.
{13876}{13934}- Öyle mi?|- Öyle.
{14514}{14596}Hacimler artmadýðý sürece|operasyonlarýn iki tarafýyla da ilgilenmende,
{14599}{14685}- bir sorun olacaðýný zannetmiyorum.|- Doðru.
{14688}{14752}Sana yardýmcý olmak için,|iki kiþi yeterli olur kanýmca
{14755}{14810}arka ofiste de|düzenlemeler için bir kaç kiþi...
{14813}{14873}Kalifiye olmalarýna gerek yok.|Gençken eðit,
{14877}{14922}aç býrak|ve onlarý eðit.
{14925}{14993}- Ben öz konuþurum, Nick.|- Kesinlikle.
{14996}{15056}Yani, bu|benim prensibimdir.
{15060}{15123}Onun yolundan gittim.|Takýmým çok gençti,
{15126}{15202}açtýlar|ve hiçbir þey bilmiyorlardý.
{15205}{15277}Gelecek anlaþmasý, daha önceden|belirlenmiþ uygun bir zamanda...
{15279}{15359}belirli fiyatta satýþlarýn|yapýlmasý için varýlan anlaþmadýr.
{15443}{15494}Pekala
{15497}{15574}Diyelim ki ben bu|cappuccino'yu satýyorum...
{15577}{15663}ancak henüz bir ay|boyunca 45 sent'im olmayacak.
{15663}{15770}Diyelim ki bunu|43 sent'e satýn aldým, Kar etmiþ olurum.
{15773}{15858}Ama fiyat öbür tarafa kayarsa,|daha fazla öderim ve kaybederim.
{15858}{15944}Bu zamanlama. Doðru zamanda|almak ve satmak.
{15947}{16011}Bazen espresso iþe yarayabiliyor|bazen de tuz ve karabiber.
{16014}{16119}Bir süper market iþletiyoruz.
{16119}{16191}Ancak bilmemiz gereken þu ki|gerçek þeyler alýp satmýyoruz.
{16194}{16272}Bunlar sadece rakam-|burada, anlaþmalar|Nikkei deðerlerine baðlý,
{16275}{16327}Tokyo Borsasý.
{16330}{16401}- Bunu banka için mi yapýyoruz?|- Hayýr, hayýr bunu alýcýlar için yapýyoruz.
{16403}{16480}Bankanýn yararýna|satýþ yapmamýz yasak.
{16484}{16535}Bunu sakýn unutmayýn,|tamam mý?
{16543}{16654}Diðerlerinin hepsi kýrmýzý giyiyordu,|kýrmýzý Çin'de uðurlu renkti
{16657}{16715}Peki sorun nedir?
{16718}{16772}Biz henüz yeniyiz.|Fark edilmemiz lazým.
{16775}{16858}- Kötü þans olur. Farklý renkler.|- Söylentiler. Kendi þansýmýzý|kendimiz yaratýrýz.
{16861}{16968}Nick doðru söylüyor.|Biz karizmayýz!
{17853}{17947}- Fernando, Tokyo'da bir geliþme var mý?|- Bir þey yok. SIMEX nasýl?
{18008}{18081}Hayýr, burada da ayný.|Kimse bu oyunu oynamýyor.
{18085}{18195}Altý yüze dayandý bile.
{18198}{18288}Burada beþ yüz seksen.|Bir satýcý iþlem talebinde|bulundu. Onaylayayým mý?
{18291}{18343}Evet.|Gebert onu.
{18346}{18413}- Kemiklerini sýk.|- Kaç tane?
{18416}{18511}Ýki yüz.|Satýn al... þimdi.
{18514}{18583}- Satýn al!|- Doldu!
{18586}{18689}- 200 için 580 ödedik.|- Bravo, Nick. 590'a sattým.
{18692}{18766}Ýþte bu süper!|Az önce 2000 kar saðladýk.
{18768}{18813}Evet!
{19020}{19084}Ýyi çocuklardý,|ve öðrenmeye de hevesliydiler.
{19087}{19161}Ýlk bakýþta insanlarýn baðýrýp|çaðýrdýðý bir deliler evine...
{19164}{19263}benziyordu. At yarýþýndaki bahisçiler|gibi... Ýçine girince buradaki|durumu daha iyi anlýyordunuz.
{19266}{19344}Arada bir sorunlar çýkýyordu|tabii ki, ama bu her alanda|karþýnýza çýkabilecek bir þey.
{19347}{19438}Özellikle bizim gibi|yenilerin karþýsýna.
{19441}{19534}Önemli olan iþi|karamaya baþlamýþtýk,
{19537}{19582}gelecek güzel gözüküyordu.
{19908}{20014}Nick baþlangýç payýyla, deðiþken payý|arasýndaki fark nedir?
{20017}{20118}Baþlangýç payý düþük ödeme gibi bir þey.|Anlaþma yaptýðýmýz kontratlardan,
{20121}{20172}yola çýkarak zamaný gelinceye|hepsini ödemeyiz.
{20175}{20271}Ancak bu arada, kontratlarýn|deðerleri de yükselip alçalabilir.
{20274}{20348}Dolayýsýyla SIMEX bizim|günlük bazdaki durumumuzu hesaplar,
{20351}{20413}ve daha fazla para isterler|eðer borsa bize karþý gelirse.
{20413}{20484}- Bu da deðiþken pay.|- Anladým.
{20488}{20537}Sanýrým.
{20599}{20659}Hatalar için hesap açmamýz gerek.|Bir kaç hatamýz oldu.
{20662}{20767}Ciddi deðil, ancak üzerinde|çalýþmaya baþlamadan önce|güvendiðim bir yere koymam gerek.
{20770}{20836}Tabii ki. Ne olarak numaralandýrayým?
{20839}{20934}- Þanslý sayýn var mý?|- Sekiz. Sekiz Çin'de uðurlu bir rakamdýr.
{20975}{21028}- Peki kaç rakama ihtiyacýmý var?|- Beþ.
{21031}{21078}O zaman hepsi de|þanslý sayýlar olsun.
{21081}{21132}Hesap numaramýz|8-8-8-8-8 hesabý.
{21672}{21752}Ve þimdi büyük bir onurla Barings Bank...
{21755}{21826}yönetim kurulu baþkaný'na|hoþ geldiniz demek istiyorum,
{21829}{21874}Peter Baring.
{22095}{22161}Dünyadaki en eski|banka olabilirdik,
{22164}{22258}ancak en önemlisi|zamana ayak uydurmaktý.
{22258}{22342}Þirketin baþýna geçtiðimde,|þunu fark ettim...
{22342}{22425}Barings'i soylular|kulübü gibi yönetemezdik.
{22428}{22473}Önümüzü bakmak zorundaydýk...
{22476}{22538}Geleneksel yapýmýzý, ve tabii ki-
{22541}{22586}eski baðlantýlarýmýzý bozmadan-
{22589}{22689}Yeni ve hýrslý|bir geleceðe baþlamalýydýk.
{22692}{22760}Artýk bunlarýn|meyvelerini de görmeye baþladýk,
{22763}{22853}ve söylemeliyim ki,|yapýlanma ve kazançlý olmamýz...
{22857}{22949}bu yeni organizasyonun|baþarýsý sayesinde olmuþtur.
{22952}{23000}Açýk söylemem gerekirse,
{23000}{23070}Güvenlik iþlerinde|para yapmanýn...
{23073}{23135}o kadar da zor|olmadýðýný fark ettim.
{23390}{23466}Doldu!
{23673}{23721}Evet, 20 için|ödedin.
{23757}{23819}Gelin.
{23853}{23918}Simon,|küçük bir problemimiz var.
{23920}{24006}Kýzlardan biri Fuji Bank'a ait|kontratlarý alacakken satmýþlar.
{24009}{24061}Pazartesi'ye kadar|hiç bir þey yapamam.
{24064}{24133}Zarar ne kadar?
{24136}{24184}Yaklaþýk iki bin kadar.
{24258}{24325}Kov gitsin.|Bir daha asla SIMEX için çalýþamaz.
{24360}{24444}- Bu biraz acýmasýz deðil mi?|- Tamam sen ilgilen.
{24448}{24551}Londra'yla konuþ, ama|müþteriyi de memnun etmeye çalýþ.
{24593}{24648}Tamam.
{24771}{24821}Bir bira alsana.
{24824}{24903}Selam hayatým.
{24906}{24962}Kim'i gördünüz mü?
{24965}{25018}Bir dakika önce buradaydý.
{25146}{25191}Kim.
{25232}{25305}Nick. Nick.|Nick, Gerçekten çok üzgünüm.
{25309}{25377}Kafama çok karýþtý.|Herkes baðrýþýp duruyordu.
{25380}{25483}Ýþimiz bu bizim.|Olunmasý gereken de o. Sakin olmak
{25486}{25542}Özür dilerim.|Sana parayý geri ödeyeceðim.
{25545}{25605}Tabii ki.|Dört yýllýk maaþýnla mý?
{25608}{25661}Ve eðer pazar hafta sonu hareket ederse,|iþler daha da kötüye gider.
{25733}{25815}Hadi, hadi, sakin ol|herkes hata yapar.
{25818}{25902}Bak, eðer þansýmýz varsa,|Pazartesi iþi halledebilirim, tamam mý?
{25964}{26054}Nick, seni bekliyordum|herkes çok iyi vakit geçiriyor.
{26058}{26118}- Ben eve gidiyorum.|- Kim!
{26121}{26203}Kim.
{26358}{26450}- Her þey yolunda mý?|- Daha iyi olamazdý.
{26453}{26500}Ben de gelip|yardým edeyim?
{26500}{26569}Bütün gün oturup|hiçbir þey yapmýyorum.
{26572}{26622}Sorun yok,|Lisa.
{26625}{26693}Becerebilirim.
{26831}{26891}Fernando, Mart'takiler ne durumda?
{26895}{26994}- Cuma günkü fiyattan|20 kontrat almam gerek.
{26994}{27091}Pazartesi ilk iþ, pozisyonu kapatmalýydým.
{27094}{27149}Ama borsanýn|deðiþmesini bekledim.
{27151}{27208}Ve o da deðiþti,|ama istediðim gibi deðil.
{27211}{27271}Þimdi daha büyük bir kaybým vardý,
{27271}{27316}artýk hepsi benim hatamdý.
{27316}{27391}Nick, duyduðuma göre|senin kýz gitmiþ.
{27394}{27449}Evet, geri gelmedi.|Hýza ayak uyduramadý.
{27452}{27531}Sadakat olmasý gerek.|Müþteriyi hallettin mi?
{27534}{27591}Tabii ki.|Hatta ufak bir kazanç bile var.
{27594}{27657}Adamým benim.
{27773}{27850}Bunlar 5-8 hesabýna.|Kayýp kontratlarý aldým.
{27852}{27932}- Altmýþ bin Pound?
{27935}{28030}- Daha önce sadece yirmiydi.|- Borsa yanlýþ yöne gitti.|Yapacak bir þey yok.
{28033}{28082}Simon Jones ne dedi?
{28085}{28158}Ciddi misin?|Bilse burayý anýnda kapatýrdý.
{28161}{28231}Her þey düzelecek. Ayýn sonundaki|hesap teslimine kadar düzelteceðiz.
{28234}{28301}- Nasýl?|- Þey, kendi hesabýmýzla oynayacaðýz...
{28304}{28395}zararý kapattýktan sonra da,|müþterinin hesabýna geçeceðiz...
{28398}{28443}ve ay sonunda açýðý kapatacaðýz.
{28447}{28508}Kumar, demek istiyorsun.
{28512}{28589}Rahatla, Bonnie.|Borsanýn kuralý bu-
{28589}{28657}Kocaman bir kumarhane.
{28796}{28851}George!
{28851}{28928}Ay sonuna kadar kimsenin|kayýtlarý kontrol
{28930}{28982}etmediðini varsayýyordum.
{28985}{29061}5-8'li hesapta bir dengesizlik olmadýðý|sürece hiç kimse,
{29064}{29133}bir þeylerin yanlýþ|gittiðini düþünmezdi.
{29136}{29212}Ancak kazanmak yerine|kaybetmeye baþladýk,
{29216}{29311}bu þekilde ben de müþterinin|hesabýndan daha çok para ödünç alýyordum.
{29547}{29616}Lanet olsun, George! Neyle oynadýðýný|sanýyorsun? Dýþarý çýk!
{29646}{29706}Hemen dýþarý çýk!
{29747}{29809}Neyle oyun oynadýðýný|sanýyorsun? Dýþarý!
{29812}{29875}Çýk dýþarý!|Tamam, dostum.
{29878}{29930}Lanet olsun!
{29996}{30072}- Tanrým, çok gerginsin.|Vücudun kaskatý olmuþ.
{30076}{30126}Nelerle uðraþtýðýmý|bilseydin anlardýn.
{30129}{30197}Bunlarýn hepsi o pisliklerin|uygun eleman almamalarý yüzünden oldu.
{30200}{30281}- Ýyi gidiyor sanmýþtým.|- Öyle zaten. Harika gidiyor.
{30284}{30360}Bütün hayatýmý baþkalarýnýn|arkasýný korumakla geçirdim.
{30360}{30431}Neden oraya gelip|sana ofiste yardým etmeme izin vermiyorsun?
{30434}{30506}- Ev hanýmý olmaktan çok sýkýldým.|- Hayýr.
{30509}{30601}Neden? Bütün iþlerle|birden uðraþman haksýzlýk.
{30604}{30653}Sinir krizi geçireceksin|diye korkuyorum.
{30656}{30720}Senin de karýþmaný istemiyorum,|Lisa. Kendim halledebilirim.
{30720}{30811}Tamam o zaman. Korkmana gerek yok.|Kimse sen beceremezsin demedi.
{30814}{30887}Lanet olasýca|bir katip olamam tekrar.
{30891}{30941}Boyacý olmayý tercih ederim.
{30990}{31055}Annem her zaman, þansýmý iyi kullanýp|eþekler gibi çalýþtýktan sonra,
{31058}{31129}istediðim her þeyi|becerebileceðimi söylerdi.
{31129}{31216}Öyle de yaptýn, deðil mi?|Çok çalýþtýn ve ödülünü aldýn.
{31219}{31287}Eminim seninle|gurur duyardý, Nick.
{31290}{31358}- Öyle mi düþünüyorsun?|- Evet.
{31361}{31416}Ben gurur duyuyorum.
{31542}{31589}Bu en kötü kýsmýydý-
{31592}{31657}Lisa benim inanýlmaz|baþarýlý olduðumu düþünüyordu.
{31661}{31733}Gerçekte iþleri|nasýl batýrdýðýmý bir bilseydi...
{31737}{31800}Borsanýn yukarý çýkmasýný|istediðim zaman, o düþtü.
{31803}{31869}Düþmesini istedim,|bu sefer çýktý.
{31872}{31923}Bunu kiþisel olarak|algýlamamak çok zordu.
{32176}{32232}Nick. Nick.
{32235}{32294}Az önce 5-8'li hesaptaki dengeye baktým.
{32297}{32378}- Kaybýmýz 1 Milyon Dolar'ýn üstünde.|- Bu kadar yüksek sesle konuþma.
{32378}{32447}Bak, panik yapmaya|gerek yok.
{32451}{32545}Müþteri hesabýnda ödeme|yapmak için yeterli para kalmadý.
{32650}{32710}Tamam.
{32765}{32849}Daha fazla Dolar.|Daha fazla Dolar'a ihtiyacým var.|Bu þekilde kaybýn üstünü örtmeliyiz.
{32896}{33001}Londra'dan para bulabilirim|bu þekilde müþteri hesabýný dengeleriz.
{33001}{33054}Anormal bir þey yok.
{33057}{33106}Ama yen'e ihtiyacým var.
{33109}{33171}Yen'le de günlük|deðiþim sütunlarýný örteceðiz...
{33174}{33229}Bu þekilde ayýn sonuna kadar|yen'leri hesapta tutacaðým.
{33276}{33353}Tabii-|Eðer seçenekleri satmazsam.
{33356}{33429}Bu þekilde|yüzdeleri sabit tutarým.
{33429}{33490}Ve 5-8'li hesaptaki|dengesizliði sýfýra indiririm.
{33599}{33649}Londra'dan para|akýþý saðlamam lazým...
{33652}{33714}Müþterinin pozisyonunu|böyle finanse edebilirim,
{33717}{33795}Pay ödemelerinde|kullanmak için de yeterli nakitim olur.
{33798}{33885}Bu týpký Paul'a|ödeme yapmak için Peter'ý soymak gibiydi.
{33888}{33988}Ama sonunda Peter! A borcumu|geri ödeyecek parayý da bulabilirdim.
{34029}{34096}Bu sýrada iþi daha da|büyütmeliydim...
{34100}{34195}nakit akýþýný açýklamak için,|daha fazla müþteriye ihtiyacým vardý.
{34225}{34270}Daha büyük daha iyi olacaktý.
{34665}{34725}Bay. Leeson,|Ben Pierre Beaumarchais.
{34728}{34828}- Çok memnun oldum.|- Bahama'lardaki|Cenova Finansal'da çalýþýyorum.
{34831}{34927}Az önce Ang Swee Tian'la görüþtüm,|SIMEX'in baþkaný.
{34931}{35022}Yürüttüðünüz miktarýn büyüklüðünden|ne kadar etkilendiðini söyledi.
{35025}{35086}- Burada fazlasýyla fýrsat var.|- Evet.
{35119}{35189}SIMEX'le birlikte|pek çok iþte çalýþýyorum.
{35192}{35237}George Sorros'la olan dýþýnda,
{35240}{35309}Muhtemelen Nikkei borsasýnda|en çok iþ yapan benim.
{35312}{35390}Bazen günde|5,000 kontrat kadar.
{35393}{35474}Bu çok fazla.|Bütün pazar zaten 20 kadar yapýyor.
{35510}{35585}Barings bu kadar|iþin altýndan kalkabiliyor mu?
{35670}{35719}Bundan emin olabilirsiniz.
{35723}{35779}Beaumarchais dualarýma|gelen cevaptý.
{35783}{35879}5-8'li hesabý ikiye|katlayacak bir fýrsattý bu.
{35969}{36020}- Alo?|- Pierre Beaumarchais.
{36023}{36088}4000 adet Haziran|kontratý almak istiyorum.
{36122}{36191}Þu an uygun olan fiyat 350 olarak gözüküyor,|ama yakýnda deðiþir.
{36194}{36258}400'den fazla ödememeye|gayret edin.
{36258}{36331}Ucuzlamýþken almalýydýk.|Beaumarchais büyük oynuyor.
{36334}{36411}Eðer bunu onun için halledersek,|o zaman kurtulabiliriz.
{36415}{36467}- Likidler ne durumda?|- Gayet iyi gözüküyor.
{36470}{36533}500'le çýkacaðýz,|sonra fiyatlar yükselecek.
{36537}{36603}Tamam o zaman. Yapmamýz gereken|diðerlerine bir þey satýyormuþ gibi gösterin.
{36606}{36669}Fiyat düþünce de alýn.|Tamam mý?
{36672}{36717}Tamam.
{36960}{37022}250. 250'yi satýn.
{37025}{37083}250'yi satýn.|240'ý satýn.
{37086}{37233}240'ý satýn.|240'ý satýn.
{37237}{37282}200'ü satýn.
{37285}{37379}200'ü satýn. Ýki yüz.|200'ü satýn.
{37382}{37433}Ýki yüz.|200'ü satýn.
{37433}{37497}- 500'lük kontrat alýn.|- 200'ü satýn.
{37533}{37596}200'ü al!
{37599}{37644}200'ü al.|210'dan satýn al.
{37647}{37711}- 210'dan satýn al. 200'den satýn al.|- 200'den satýn al.
{37714}{37776}- Satýn al, satýn al! 200'den satýn al.|- 220'den satýn al.
{37779}{37826}- Doldu!|- 230'dan satýn al. 230'dan satýn al.
{37829}{37891}- 230'dan satýn al! 240'dan satýn al!|- 240'dan satýn al!
{37894}{37939}250'den al!
{37993}{38055}Doldu.
{38157}{38271}Kimse bir þey fark etmedi. Ýlk|1500'ünü biz kapmýþtýk bile.
{38274}{38388}- Tam dört bin kontrat.|- Harika oldu.|Ýþte bu harika oldu!
{38833}{38879}Sonunda þansým dönmüþtü.
{38883}{38952}Bu sefer de|sürekli kazanýyorduk.
{38955}{39060}Nikkei'de çok baþarýlý olduk. Yani,|kumar oynamaya devam ediyorduk.
{39063}{39126}Daha yukarý.|Yukarý, Yukarý, Yukarý
{39292}{39357}Çok iyi. Çok çok iyi.
{39766}{39824}Eðer 19,000'e çýkarsak,
{39827}{39897}sattýðým bütün|seçenekler elimde oluyordu
{39977}{40057}Hadi bebeðim.|Hadi bebeðim, baþarabilirsin. Hadi.
{40246}{40338}Bonnie, iþte bu çok heyecanlý!
{40338}{40385}Evet!
{40427}{40505}Bence baþaracaðýz.
{40596}{40646}Evet!
{40649}{40713}Ýnanýlmaz bir þey.|Bütün kayýplar -
{40716}{40765}kapandý.
{40768}{40828}Sana ne demiþtim,|biraz inancýn olacak.
{40831}{40896}Böyle devam ederse,|bu katlamaya devam eder...
{40899}{40956}Sen kazanmaya endekslenmiþsin.
{41553}{41605}- Mutlu musun?|- Evet. Sen?
{41608}{41653}Daha iyi olmamýþtým.
{41727}{41772}Oldukça zor günler|geçirdim iþte.
{41775}{41820}Seni üzmek|istememiþtim.
{41823}{41893}- Ne demek istiyorsun?|- Hayýr, sorun yok.
{41893}{41985}Borsa tersine döndü, ve|bütün iþler iyiye gitti.
{41988}{42033}Hepsini geri kazandým.
{42037}{42112}Ne demek|istiyorsun, Nick?
{42115}{42174}Hemen heyecanlanmaný istemiyorum,|ama bir kaç hata yaptýk...
{42177}{42224}ve bazý kayýplarýmýz oldu.
{42228}{42280}Geri kazanmak için|biraz oyun oynadým.
{42283}{42331}Þey, kayýplar|ne kadardý peki?
{42361}{42438}- Bir Milyon Dolar civarýnda.|- Bir Milyon mu?
{42441}{42493}Aman tanrým, Nick.
{42526}{42594}Hayýr sorun yok.|Hesap kapandý. Ýkiye katladý.
{42594}{42661}Çocuklarý korumak|için böyle yapmam gerekiyordu.
{42713}{42781}Peki, ama bunu bir daha|yapmayacaðýna dair bana söz ver.
{42784}{42849}- Buna deðmez, Nick.|- Söz veriyorum.
{42898}{42948}Kalp krizi|geçirecektim neredeyse.
{43070}{43133}- Mutlu Noeller.|- Mutlu Noeller.
{43327}{43378}Çekin gidin.
{43434}{43479}Sonunda baþarmýþtým.
{43482}{43530}Þehrin bir numarasý|en olmuþtum.
{43533}{43589}Ve yeni yýl geldiðinde,|5-8'li hesaba olan...
{43592}{43642}baðýmlýlýðýmý|sonsuza dek sona erdirecektim.
{43646}{43691}Borsa hakkýnda ne düþünüyorsun,|Nick, uzun vadede tabii?
{43694}{43757}Uzun vadede mi? Þaka mý yapýyordun?|Kimse iþin uzun vadesini düþünmez.|Saliseler düþünülür.
{43761}{43819}- Uzun vade yarýn sabah demektir.|- Tamam, yarýn sabah, o zaman.
{43822}{43870}Bu olabilir iþte.
{43873}{43953}- Leeson söyler, borsa dinler.|- Sen söyledin, dostum.
{44005}{44077}- Pierre.|- 220 arama seçeneklerini satmak istiyorum...
{44079}{44133}ve Aralýk'taki 200|aramalarýný satýn al.
{44136}{44213}0,138'lik bir teklifim var.
{44216}{44271}Daha iyisi olmaz mý?
{44274}{44372}- Sana geri döneceðim.|- Çabuk ol, Nick.|Hýzlý hareket etmeliyim.
{44475}{44537}Neden birden,|0,138'liklerin peþine düþtü bu?
{44541}{44624}220 aramalarý düþüþte.|Zararýný kapatmak istiyor.
{44627}{44688}- Evet ama neden 0,138?|- Bu bir oran.
{44691}{44750}200 aramalarý|1,400 üzerinden anlaþýyorlar.
{44753}{44850}200'ü 1,400'e böl,|sonuç 0.143.
{44853}{44911}Tamam,|ama 0.138 deðil.
{44914}{44992}Belki de birisi ona|iþ için bir indirim yapýyordur.
{44995}{45092}Societe Generale olabilir.|O pisliklerin onu almasýna izin veremeyiz.|Pierre en büyük müþterimiz.
{45095}{45161}- Ne yapacaksýn?|- Düþüreceðim.
{45164}{45249}Yani, Pierre'den alýp borsa düþünce de|geri mi satacaksýn?
{45253}{45297}Banka için çalýþmamamýz|gerek diye biliyordum.
{45301}{45368}Pierre, Yapabilirim.|Tam geniþliði söyler misin?
{45371}{45466}6,500 mü? Tamamdýr.|Bana býrak. Sorun yok.
{45466}{45536}Ya borsa yükselmezse?|Düþüþe geçerse ne olacak?
{45539}{45624}Daha önce oynadým ve kazandým.|Tekrar ayný þeyi yapabilirim.
{45627}{45705}Harika olacak çocuklar,|bana inanýn.
{45993}{46090}Bonnie, 5-8'li hesabý|tekrar açmaný istiyorum.
{46093}{46140}Herifin kontratlarýný|deli gibi çalýþtýrdýk...
{46144}{46228}þimdi de bize tekmeyi basýp|Societe Generale'e dönmeyi düþünüyor.
{46232}{46333}Londra'ya Brenda Granger'a faks çek|ödemeleri örtmek için daha çok fon iste.
{46336}{46419}Müþterinin lehine de.
{46422}{46493}- Alo?|- Nick, ben Simon.|Ofisime gelebilir misin?
{46496}{46585}- Seni hemen görmem gerek.|- Kahretsin, Bir þeyleri anladý.
{46588}{46652}Biraz uzun sürdü ama.
{46654}{46738}Lisa'ya ne diyecektim?|Beni öldürecekti.
{46741}{46786}Ýçeri gir.
{46912}{46957}Tebrikler,|Nick.
{46960}{47045}1993 bonuslarý geldi,|ve sen 135.000 getiride bulundun.
{47078}{47135}1-3-5?|Bu olaðanüstü!
{47138}{47241}Küçük takýmýn 10 Milyon Pound'ýn|üzerinde kar getirdiniz.
{47241}{47314}Sen bir yýldýzsýn.
{47317}{47406}Aslýnda kazanç o kadar yüksek ki,|bir kontrol yapýlmasý gerekiyor.
{47409}{47456}Kontrol mü yapacaklar?
{47459}{47553}Evet bunun için Ash Lewis|gelecekmiþ.
{47556}{47638}Merak etme. Sadece bürokrasi.
{47642}{47687}Ash Lewis mi?
{47690}{47760}Biraz zor birisi|olduðunu duymuþtum, doðru mu?
{47950}{48001}Burasý bizim bölüm.
{48052}{48097}Doldu, doldu.|250 ödendi.
{48100}{48145}Selam, Nick.
{48148}{48198}Bu Ron Baker|ve Ash Lewis.
{48201}{48247}Ron Lonra'daki|pazarlamanýn baþýnda yer alýyor.
{48250}{48302}- Bu da beni senin patronun yapýyor, Nick.|- Memnun oldum.
{48305}{48385}- Nasýlsýnýz, Bay Leeson?|- Çok iyiyim, teþekkür ederim.
{48387}{48436}Tamam, hareketlere|bir bakalým.
{48492}{48537}Henry!
{48540}{48601}Peki bütün iþleri kim yapýyor?|Biz en büyüðüz, deðil mi?
{48605}{48669}Þey, biz daha çok arbitrajla uðraþýyoruz,|Yüksek bir volümde çalýþýlýyor.
{48672}{48741}Bütün istekleri þurada|duran George'a gönderiyoruz.
{48744}{48807}Bu Henry. Ve günün sonunda|kýzlar ofiste,
{48809}{48875}bütün anlaþmalarý|bilgisayara aktarýyor.
{48878}{48932}Siz hem pazarlama|alanýnýn...
{48935}{48993}hem de düzenleme kýsmýnýn,|baþýndasýnýz deðil mi?
{48993}{49041}Evet. Henry, 100'de|iþaret ver. Evet, evet.
{49044}{49093}Bu çok garip.
{49096}{49144}Çekler ve dengelere|ne oldu peki?
{49147}{49192}Bu konuda konuþmamýz gerek.
{49195}{49245}Üç hafta boyunca burada olacaðým.|Bu oldukça...
{49249}{49301}geniþ bir araþtýrma olacak.
{49305}{49350}Etraflýca kontrol etmem gerek.
{49353}{49402}Kesinlikle.|Her konuda yardým ederim.
{49405}{49464}Bir þeye ihtiyacýnýz olursa,|bana haber verin yeter.
{49467}{49552}Doldu mu? Harikasýn, Henry.|Seni görmek güzeldi, Simon.
{49673}{49742}Babam Blackheath'teki daireyi|görmüþ, oldukça da beðenmiþ.
{49744}{49805}Biraz uðraþmak gerekiyormuþ,|ama o ve büyükbabam hallederler.
{49808}{49881}Sigorta gibi düþün|kötü bir þey olursa,
{49884}{49942}Ýngiltere'ye dönüp|boyacýlýk yaparsýn.
{50038}{50121}Senin neyin var?|Ýyi misin?
{50125}{50214}Ne yapardýn, Lise?|Eðer batsaydým ne yapardýn?
{50217}{50308}Daha yeni büyük|bonus aldýn.
{50311}{50398}Evet, ama ya iþler ters giderse?|Ya herkesin düþündüðü kadar zeki deðilsem?
{50400}{50446}Elbette öylesin tatlým.
{50448}{50544}Her neyse, be seni seviyorum.|Parayla ilgilenmiyorum.
{50547}{50595}Bana kalsa her þeyi|býrakýp Ýngiltere'ye döner...
{50598}{50649}ve aile kurardým.
{50691}{50761}Harika gidiyorsun,|Nick.
{50764}{50815}Lanet olasýca bir yýldýzsýn.
{51067}{51114}Nick?
{51150}{51214}- Nick.|- Kahretsin. Simon.
{51217}{51268}Ne oldu?|Çok mutlu gözüküyorsun.
{51271}{51362}Duymadýn mý? Olaðanüstü hal bitti.|Ash Londra'ya geri döndü.
{51365}{51425}- Þaka yapýyordun. Neden?|- Ofis kurallarý8.
{51428}{51506}Baring Gelecek ve|Baring Güvenlik arasýnda bir þeyler olmuþ.
{51509}{51615}- Peki ya denetim?|- Mark Taylor ve Chris Carr'ý gönderiyorlar.
{51618}{51690}Ash'le karþýlaþtýrýnca,|ikisi de zavallý.
{51694}{51761}Yazýk oldu. Þu ünlü|Ash Lewis'i iþ baþýnda...
{51764}{51827}görmek isterdim.
{51879}{51924}Tabii!
{52019}{52064}Hayýr, Tam|dýþarý çýkýyordum.
{52067}{52115}Tamam ben de|hemen duþa girip geliyorum.
{52118}{52178}- Eve önce sen gelirsen,|fýrýný açar mýsýn?|- Tamam tatlým.
{52181}{52228}- Görüþürüz.|- Görüþürüz hayatým.
{52411}{52466}- Binsene pislik.|- Bu da nereden çýktý?
{52470}{52566}Yakýyor deðil mi?|Bir Porsche, moron. Binsene!
{52649}{52700}Ne olduðunu|söyleyeceðim.
{52703}{52754}Ýðrenç bir þey bu.
{52754}{52845}Ne olduðunu söyleyeyim:|Bu muhteþem.
{52898}{52943}Bonus'umla yapacak|bir þey bulmalýydým.
{52946}{53011}Gözünü yoldan ayýrmasana.
{53209}{53278}Burasý tek|yönlü yol, George.
{53344}{53437}Ýnanamýyorum!|Ýþte bu harika!
{53837}{53905}Kahretsin!|Þu Reuters'den bir gazeteci.
{53908}{53981}- Nick. Nick.|- Haftalardýr röportaj için peþimde.
{54039}{54085}- Hey, Nick.|- Selam, dostum.
{54122}{54193}- Tamam, Loy?|- Nick, adamým. Ne içersin?
{54196}{54262}Bira, lütfen. George Seow'u bilirsin,|benim için çalýþýyor.
{54265}{54346}Nasýlsýnýz. Bu da|Intercontinental Trading'den|Danny Argyropoulis.
{54349}{54435}- Memnun oldum, Danny.|- Evet, ben de memnun oldum, dostum.|Hakkýnda çok þey duyduk.
{54435}{54534}Barings burada senin|sayende tutunmuþ.
{54537}{54607}Þey, bilirsin, bu konu hakkýnda|fazla abartýlý dedikodular var.
{54610}{54655}Bu kadar alçakgönüllü olma.|Ona ne dediklerini biliyor musun?
{54658}{54703}- Ne diyorlar?|- Kambiyonun kralý.
{54706}{54766}SIMEX Barings'e yürüttüðü|iþler yüzünden bir ödül verdi.
{54769}{54838}- Nasýl gidiyor? Ýyi miyiz?|Bira alayým.|- Bira ister misin?
{55496}{55559}Buna da|derinlik hesabý deniyor.
{55562}{55638}Kafaný uçurur ona göre.
{55673}{55733}- Hazýr mýsýn?|- Hadi yapalým.
{55737}{55782}- Tamam o zaman.|- Baþlayalým.
{55785}{55895}Bir, iki, üç!
{55898}{55946}Þerefe.
{56264}{56354}Güzel bayanlar,|siz ne bekliyorsunuz?
{56354}{56412}Hadi!
{56415}{56461}- Ýçeri girin!|- Ýyi þanslar, George.
{56464}{56525}Bir nedenle,|bu gece caziben pek iþlemiyor.
{56529}{56618}Pis kaltaklar.|Eminim hava yolunda hosteslerdir.
{56621}{56694}Uçuþ görevlisi,|sakýncasý yoksa.
{56785}{56834}- Uçuþ görevlisi.|- Ne istiyorlar?
{56900}{56955}Girmek isteyip|istemediklerine...
{56957}{57020}karar vermelerine yardýmcý olsana.
{57023}{57073}Yardým edelim o zaman.
{57121}{57186}Karar vermen kolaylaþýr.|Hadi. Utangaç olma.
{57189}{57256}Annen hiç de öyle deðildi.
{57260}{57305}Bu adamý seviyorum.
{57307}{57354}- Üçe kadar sayalým mý?|- Daha önce iþe yaradý.
{57358}{57431}- Þimdi de yarar.|- Bir,
{57431}{57491}Ýki, üç.
{57491}{57550}- Þerefe!
{57553}{57654}Bu iðrenç!
{57769}{57840}Kesinlikle harikasýn, Nick!|Ýçkiler benden.
{57843}{57898}Bu derinlik sarhoþluðu|benim gemimi batýracak.
{58047}{58093}- Kahretsin. Saat kaç?|- Bilmiyorum.
{58096}{58148}- Lisa'yý aramalýyým. Telefon.|- Ara bakalým.
{58344}{58451}- Þaka yapýyor olmalýsýn.|- Gülünecek bir þey yok.
{58454}{58558}Bayanlarý rahatsýz etmek|Singapur'da büyük bir suçtur.
{58674}{58723}Ve bu haber Londra'ya da ulaþtý...
{58726}{58797}en yüksek noktaya.
{58797}{58870}Utanç verici bir þey,|elemanlarýmýzdan birisi...
{58874}{58939}dün gece sarhoþ olup|ay ýþýðý yapmýþ.
{58942}{58988}Ne dedin?
{58992}{59064}Poposunu göstermiþ.
{59067}{59143}- Neden?|- Oyun oynuyorlardý, herhalde.
{59146}{59226}Ne yazýk ki oradaki kanuna|hücreye atýlmasý gerekiyor.
{59229}{59282}Belki de|onu kovmalýyýz.
{59285}{59390}Þimdi kovmak biraz garip olurdu,|en azýndan...
{59392}{59491}Uzak Doðu'daki karlarýmýzýn çoðunun ondan|kaynaklandýðýný düþünürsek.
{59491}{59574}Þey, þunu da söyleyeyim aslýnda Ýngiltere|Bankasý da bizim orada bulunan...
{59577}{59639}bütçemizin büyüklüðüyle|ilgili laf atmaya baþladý.
{59643}{59755}Teknik olarak ana parayý düzenleme|kurallarýný ihlal ettiðimi söylenebilir.
{59758}{59849}Kulaklarýna bazý|þeyler fýsýldamamý ister misiniz?
{59852}{59902}Hayýr, henüz o noktada deðiliz.
{59905}{59988}Bankadan Andy Dixon'la konuþtuðumda,|bana asýl sorunun, þey,
{59991}{60069}kendinde yattýðýný söyledi.
{60071}{60120}Zayýflamaktan rahatsýz.
{60123}{60180}Aslýnda haklýlar.|Birilerinin kontrol etmesi gerek.
{60183}{60244}Karar bu mudur o zaman?|Baþka bir þey var mý?
{60247}{60297}Þey, Leeson|konusunda ne yapacaðýz peki?
{60300}{60358}O ve teþhirci yanýyla ilgili?
{60361}{60479}Bence bu konuyu|Singapur yetkililerine býrakmalýyýz.
{60483}{60571}Buna katýlmak durumundayým.
{60708}{60771}Yani beni koruyan kazancýmýz mýydý?
{60774}{60819}Eðer bilselerdi.
{60889}{60982}Nick, þu Reuters'deki adam yine arýyor.|Bu bugün ikinci.
{60985}{61039}Þeyde olduðumu söyle-
{61042}{61092}Boþ ver.|Ver þu telefonu.
{61124}{61188}5-8'li hesaptaki dengeleri|basar mýsýn lütfen?
{61191}{61278}- Selam, Loy. Sorun nedir?|- Nick. Sana ulaþmak ne kadar da zormuþ.
{61282}{61340}Buradaki yoðunluðu biliyorsun.|Senin için ne yapabilirim?
{61344}{61425}- Þu satýn aldýklarýn konusunda.|- Biz memnunuz.
{61428}{61482}Müþterinin memnuniyeti|bizim için önemli olan þey.
{61485}{61572}Bu gizemli müþteri kim, Nick?|Oldukça güçlü olmasý lazým.
{61575}{61620}Üzgünüm, dostum.|Kurallarý biliyorsun.
{61623}{61673}Müþteri gizliliði falan.
{61676}{61731}Müþterin, Pierre Beaumarchais'mu?
{61761}{61812}Üzgünüm, Loy.
{61815}{61860}Gitmek zorundayým.|Sonra konuþuruz.
{61863}{61942}Bir ara seninle|konuþacaðým.
{61945}{62036}Kahretsin, Bonnie.|Burada 7.78 Milyar Yen var.
{62040}{62095}Dolar kurundan mý istiyorsun?|Bir dolar yüz yen-
{62099}{62149}Evet evet,|77.8 milyon dolar.
{62153}{62199}Evet. Bana bir sonraki|ulusal anlaþmada yer ayýr.
{62201}{62265}1,000 sat|21 Aralýk'ta,500.
{62268}{62338}7-7-7-8 fiyatýna|seçenekleri yerleþtir.
{62341}{62389}Onu girdikten sonra|yeni raporun çýktýsýný getir,
{62392}{62486}Demek þu anda SIMEX bize|7.78 Milyar yen borçlu gözüküyor.
{62489}{62535}Tamam, Nick.
{62538}{62637}Ve, þey, bunu Londra'dan Brenda|Granger'a faksla daha fazla bütçe iste.
{62640}{62701}Bir müþteriden geniþ çapta|bir istek geldiðini söyle.
{62704}{62766}- Ne kadar?|- Bir milyon.
{62769}{62814}Ýki olsun.
{63021}{63066}- Nick.|- Efendim?
{63105}{63160}Nick, telefon.
{63297}{63352}Alo?
{63355}{63419}- Rahatsýz etmiyorum deðil mi?|- Saat gece 2:00.
{63422}{63478}Kahretsin, doðru dostum.|Tamamen unutmuþum.
{63481}{63534}Dinle sorun var,|buradaki kodamanlar rahatsýz durumdalar.
{63536}{63587}Durumu biraz küçültmeni|istiyorlar.
{63590}{63639}Bu söylendiði|kadar kolay deðil, Ron.
{63639}{63689}Borsaya yanlýþ|bir mesaj göndermiþ oluruz.
{63693}{63769}Evet evet. Bu arada þu anda iki|milyonluk bir kazanca ihtiyacýmýz var...
{63772}{63828}gelecek aya|bonuslarý korumak için.
{63831}{63919}Ýki milyon mu?|Ron, sen hangi gezegende yaþýyorsun dostum?
{63922}{63974}Biraz önce benden iþi|küçültmemi istiyordun, þimdi de-
{63977}{64050}Baþarýsýz olma gibi bir þans yok dostum.|Sana güveniyoruz.
{64050}{64116}Üç haftaya kalmaz|Londra'da çöp toplamaya baþlarsýn.
{64244}{64294}Ýki milyon mu?
{64297}{64358}Beni kim zannediyorlar,|George Sorros'mu?
{64430}{64485}Diðer yýlýn|sonuna yaklaþýyorduk,
{64489}{64549}bu yýlbaþýnda|baþýmdaki bela daha büyüktü.
{64553}{64632}Barings beni Londra'daki bir|konferansa konuþmacý olarak çaðýrmýþtý.
{64635}{64736}Onlar için bir yýldýzdým, ve tek bilmek|istedikleri iþin sýrrýný öðrenmekti.
{64772}{64845}Düþünmeden edemiyordum.
{64848}{64898}Nan Karen|Hala'yla mý kalýyormuþ?
{64901}{64965}Evet olabileceði|en iyi yer orasý.
{64968}{65026}Zavallý.
{65029}{65102}Sürekli aðlýyordu|deðil mi?
{65152}{65214}Alo?
{65217}{65266}Nick, telefon sana.
{65269}{65315}Ron Baker mý?
{65487}{65566}Ron. Beni bulabildiðine|inanamýyorum.
{65569}{65614}Dinle, þu konferansla ilgili,
{65617}{65673}uzun bir süre pazarlama|kýsmýndan uzak kalacaksýn.
{65676}{65750}Þu cenaze için zaten|bir hafta erken gelmem gerekiyor.
{65753}{65808}Lisa'nýn büyük babasýndan|bahsetmiþtim sana.
{65811}{65888}Evet üzgünüm dostum,|ama burada senin kazancýn için uðraþýyorum.
{65891}{65941}Bu kazançlarý|toplaman gerek.
{65944}{66016}- Cenazeye gitmek zorundayým.|- Yine gidersin.
{66016}{66063}Sana özel|vize ayarlayacaðým...
{66066}{66115}Böylece Pazar günü gelirsin|ve gece boyunca çalýþýrsýn.
{66119}{66180}Saat farký ile,|hiçbir þey kazanmazsýn.
{66184}{66232}Yolumdan çekil!
{66276}{66366}Eðer bu kadar sýký çalýþýyorsa,|yemeðe ihtiyacý olacak.
{66368}{66447}Pazar gecesi ofise|gidip çalýþmamý istiyorlar.
{66447}{66516}Hayýr. Bu kesinlikle|düþünülemez bile.
{66519}{66584}Yeter artýk|baþkasý uðraþsýn þu lanet þeylerle.
{66587}{66639}Haklý, Nick.|Sen robot deðilsin.
{66642}{66732}Tam bonus zamaný. Eðer ulaþtýrmazsam,|o zaman herkes kaybeder.
{66735}{66780}Bu hiç adil|deðil, Nick.
{66783}{66837}Bu þekilde devam edersen,|yakýnda yataða düþeceksin.
{66841}{66887}Yakýnda senin cenazene gideceðiz.
{66890}{66966}"Yüce tanrýmýz|geride kalanlarý kutsasýn,
{66970}{67052}büyük merhametini,|burada ayrýlan...
{67055}{67103}kardeþimizden mahrum|býrakmasýn,
{67106}{67210}Burada|bedenini topraða veriyoruz.
{67212}{67352}Dünya dünyaya,|küller küllere, tozlar toza."
{67421}{67467}Seni gördüðüme memnun oldum evlat.
{67469}{67515}Böyle görüþmek istemezdim,|ama ne yaparsýn.
{67518}{67571}- Çok iyi niyetliydi.|- En önemlisi de o.
{67606}{67656}Ýþler nasýl gidiyor peki?
{67660}{67744}- Þikayet edemem.|- Hepimiz seninle gurur duyuyoruz, Nick.
{67748}{67818}- Önemli bir þey deðil.|- Bu kadar alçakgönüllü olma.
{67820}{67880}Sen bir boyacý oðlusun.
{67883}{67936}Keþke annen de|bugünleri görseydi.
{68001}{68046}Keþke.
{68075}{68134}Seni utandýrmamaya|çalýþacaðým, baba.
{68137}{68211}- Ne dedin sen?|- Önemli deðil. Yol yorgunluðu.
{68214}{68268}Siz bana bakmayýn.
{68389}{68434}Ofise gidip aylardýr kaçtýðým,
{68437}{68519}insanlarý görünce|çok kötü oldum.
{68522}{68582}Ýnsanlarý telefonda|kazýklamak baþka bir þeydi,
{68582}{68644}ama þimdi yüz yüzeydik.
{68648}{68718}Nick?|Ýnanamýyorum sen misin?
{68722}{68806}Nick Leeson?|Geleceðini duymuþtum.
{68809}{68919}- Kim olduðumu bilmiyorsun|bile deðil mi?|- Brenda?
{68922}{68977}- Tabii ki. Çok üzgünüm. Nasýlsýn?
{68980}{69054}Sonunda yüzünü de|görmüþ olduk böylece.
{69057}{69102}Aman tanrým,|çok gençmiþsin.
{69105}{69152}Yaþlanýyoruz tabii.
{69155}{69203}Bak, Nick, neden|ofisime gelmiyorsun?
{69206}{69263}Seninle bazý rakamlar|hakkýnda konuþmak istiyorum.
{69266}{69323}Brenda, Peter Norris'le|birazdan bir toplantým var.
{69326}{69391}Tamam, o zaman|sonra bana uðra, tamam mý?
{69395}{69457}Orasýyla ilgili sorularýmýza|bir tek sen cevap verebilirsin.
{69460}{69540}Bu arada yeni|bir fon da istediler.
{69540}{69588}- Tamamdýr. Bu mu?|- Evet.
{69588}{69645}- Tamam.|- Görüþürüz.
{69647}{69705}Brenda benim nakit çeþmemdi.
{69705}{69767}Garip sorular sormasýný|istediðim son kiþide oydu.
{69770}{69871}- Nick'le tanýþmanýzý istiyorum-|- Ama önce Peter Norris'le...
{69874}{69921}Ýþinde inanýlmazdýr,|Onun için...
{69924}{69992}- gece gelip Nikkei'deki iþleri.|Halletmesini istedim- Gerçekten mi?
{69995}{70113}Nick'i iþten uzak tutamazsýn.|Singapur'daki kilit adamýmýz.
{70115}{70197}- Asya'daki büyük adam sensin demek.|- Normal deðil bu adam.
{70201}{70278}- Borsayý ele alýþýný görmelisiniz.|- Hoþuna gidiyor mu?
{70281}{70355}- Fena deðil.|- "Fena deðil mi"?
{70452}{70497}Þimdi þu birleþen satýþ...
{70500}{70545}alanlarý ile ilgili|konuþmamýz gerekiyor.
{70548}{70653}Nick'in bazý düþünceleri var.|Eðer onun baþarýsýný geniþletirsek-
{70682}{70727}Ne dersin, Nick?
{70730}{70785}Birleþtirmek çok iyi bir fikir.
{70788}{70873}Tabii kontroller yapýlmalý
{70876}{70962}Ancak ticaret kitaplarý|destekleri saðlamak...
{70966}{71072}müþteri istekleri|bilgi açýklarýnýn yükselmesi...
{71075}{71125}ile ilgili bilgi verir.
{71129}{71174}Kesinlikle katýlýyorum.
{71177}{71231}Görüyorsun, Peter,|Nick katýlýyor.
{71234}{71279}Müþteriyle iletiþimi de|çok baþarýlý.
{71282}{71341}Ona bayýlýyorlar.
{71344}{71407}Evet, muhteþem.|Ýþler böyle devam etsin.
{71407}{71491}Ron, þimdi açýkla bakalým|birleþtirici planlarýný.
{71494}{71539}Þimdi, beyler,|söylemem gerek ki-
{71542}{71587}- Tanýþtýðýmýza memnun oldum.|- Memnun oldum.
{71590}{71635}- Þerefe.|- Görüþürüz.
{71683}{71754}Ýyi gitti, öyle deðil mi?|Birleþtirici fikrini beðendi.
{71757}{71809}Tabii ki, Ron.|Kesinlikle beðendi.
{71813}{71858}Bu senin için de iyi olacak.
{71861}{71932}Sana artýk yeni|bir sýfat bulurlar.
{71932}{72002}Bir dakika bekler misiniz?|Nick?
{72029}{72074}Nick?
{72077}{72138}Ron?
{72280}{72391}Ýyi olmak|yeterli deðil.
{72394}{72488}Herkes stratejimize|inanmalý,
{72491}{72590}inanmayan varsa|kendisi kaybeder.
{72645}{72728}Arbitraj danýþmanlýðý|bizim iþimiz.
{72732}{72834}Eðer bilgi eðrisinden|haberiniz yoksa öðrenin.
{72837}{72954}Kendinizi bir bilgi eðrisine odaklayýn.
{72957}{73013}Eðriyi yönlendirin.
{73016}{73061}Nick Leeson,
{73064}{73134}çoðunuz onun ismini|duymuþsunuzdur eminim,
{73137}{73191}Singapur'daki iþlerimizi|yürütüyor,
{73194}{73277}Siz onu da aþmalýsýnýz.
{73277}{73360}Neler yaptýðýný Nick'ten de|duyacaksýnýz tabii ki,
{73364}{73448}benim belirtmeye|çalýþtýðýmý þey þu...
{73452}{73529}eðer Nick hakkýnda|biraz düþünürseniz...
{73532}{73636}veya onun adýmlarýndan|gidecek fikirler üretirseniz,
{73639}{73779}o zaman Barings bu|sektördeki en güçlü
{73782}{73833}kurum olacaktýr.
{73951}{74009}Kahretsin!
{74012}{74147}Fazlasýyla para yapacaðýmýzdan|emin olabilirsiniz.
{74151}{74206}Evet iþte bu,
{74210}{74265}çok çok fazla...
{74269}{74356}para... yapacaksýnýz...
{74877}{74926}Nick.
{74954}{75024}- Nick, uyan.|- Lisa.
{75028}{75103}- Akþam yemeðine gitmemiz gerekiyor.|- Yapamam.
{75103}{75163}Kaldýramýyorum.|Artýk dayanamýyorum.
{75167}{75217}Geri dönmek istemiyorum.|Bana bunu yaptýrma.
{75219}{75317}Neden bahsediyorsun sen? Peter|Norris'in yanýndaki koltukta oturacaksýn.
{75320}{75377}Sakýn bana sunumu da|kaçýrdýðýný söyleme.
{75380}{75444}- Ýçiyordum.|- Ýnanmýyorum sana.
{75447}{75496}Bu yaptýðýn çok kaba.|Seni bekliyorlardý.
{75499}{75579}- Böyle yüzüstü býrakamazsýn insanlarý.|- Anlamýyorsun, Lisa.
{75582}{75667}Patlamak üzere olan bir yanardaðýndayým.|Geriye gidemem.
{75670}{75725}Bonuslar ne olacak peki?
{75728}{75789}Mýzlanmayý kes|ve giyinmeye baþla.
{75792}{75897}- Sana yanardaðýný göstereceðim,|Nick Leeson, ayaða kalk.
{75900}{75954}- Kokuyorsun, gir þunun içine.|- Buna ihtiyacý- Lisa!
{75957}{76022}Lisa.
{76090}{76164}Seni kaltak.
{76167}{76233}- Þimdi seni öldüreceðim.|- Þu haline bak.
{76236}{76295}Ýðrenç gözüküyorsun.|Þu haline bak.
{76297}{76354}Beni de ýslatacaksýn|dur! Nick!
{76495}{76583}- Nick?
{76587}{76656}Hemen giyinmelisin.|Kes.
{76659}{76718}Giyinmen gerek!
{76893}{76972}Bana söz ver|beni hep seveceksin, Lisa.
{76975}{77042}Ne olursa olsun,|yine de seveceksin.
{77045}{77103}Tabii ki seveceðim.
{77106}{77169}Sen benim adamýmsýn,|unuttun mu?
{77365}{77416}Geri dönmek çýlgýncaydý.
{77420}{77483}Sene sonu kontrolünü|nasýl anlatacaðýmý bilmiyordum.
{77486}{77556}7.78 Milyar Yen'lik|küçük sorun...
{77559}{77638}hesaptaki deliði|tamamen ben yaratmýþtým.
{77641}{77710}Bir fýrsatýný bulup|Lisa'ya söylemeliydim,
{77713}{77758}ama içimden bir ses,
{77761}{77838}bana daha önce açýklarý kapattýðýmý|bir kere daha yapabileceðimi söylüyordu
{77878}{77932}Bu mektup nedir?
{77992}{78037}SIMEX'ten gelmiþ.
{78040}{78121}SIMEX'ten olduðunu görüyorum.|Sen yokken geldi.
{78123}{78192}"Görünüþe göre|þirketiniz pozisyonlarý saðlarken...
{78195}{78273}8-8-8-8-8 numaralý bir alt hesap kullanýyor.
{78276}{78349}Bu durumda,|ihlal etmiþ olduðunuz 8-2-2 sayýlý...
{78353}{78396}kural üyeleri müþteriler için|pazarlýk yapmaktan...
{78399}{78445}alýkoyar."
{78448}{78517}Sadece gün içi|fon limitlerinden bahsediyorlar.
{78520}{78590}Peki bu bahsettikleri|8-8-8-8-8 hesabý ne?
{78593}{78668}Müþteri hesabý.|Çok fazla hesabýmýz var,
{78671}{78720}o yüzden bakmam gerek.
{78723}{78825}Þu an kentte bir numarayýz,|bizi baðlamaya çalýþýyorlar.
{78828}{78884}Bunu isteyecek durumda|kim var?
{78887}{78933}Bu konuda bir|cevap vereceðim.
{78937}{79011}Bekliyorum tamam mý?|Sabaha masamda olsun.
{79014}{79074}Tabii ki, Simon.
{79272}{79322}Lisa?
{79428}{79473}Lisa?
{79707}{79752}Lisa, ne yapýyorsun?
{79789}{79832}Kanýyorum, Nick.
{79990}{80035}Neden bana söylemedin?
{80038}{80126}Emin olana kadar beklemek istedim.
{80129}{80185}- Bana kýzgýn deðilsin deðil mi?|- Sana kýzgýn deðilim.
{80185}{80230}Tabii ki sana|kýzmadým aþkým.
{80230}{80302}- Bebek istiyorsun deðil mi, Nick?|- Gerçekten de bebeði istiyorum.
{80305}{80354}Hatta bir sürü|bebek istiyorum.
{80357}{80414}- Öyle mi?|- Öyle.
{80760}{80819}Karýnýzýn durumu iyi.
{80822}{80880}Maalesef|bebeði kaybettik.
{80902}{80952}Üzgünüm.
{81344}{81389}Kýrýlma noktasýna gelmiþtim.
{81392}{81475}Artýk borsanýn|benim yararýma ilerlemesi,
{81479}{81540}umudumdan vazgeçtim.
{81542}{81616}Ben kýpýrdamasýný saðlayacaktým.
{81619}{81677}Ne kadar para|tutmasý önemli deðildi.
{81680}{81741}Sonuna kadar gidecektim.
{81790}{81861}Adam tek baþýna|grubun beþinci...
{81864}{81914}büyük kazancýný saðlýyor.
{81917}{82009}Biliyorum, Ron. Ama 30 milyon dolar|pay ödemesi için mi?
{82012}{82073}- Bir günlük alým satým için mi?|- Hayýr anlamak istemiyorsun.
{82076}{82181}Hacimler çok büyük. Nick'in adamý|SIMEX'te büyük güce sahip.
{82309}{82387}- Alo?|- Nick, Ben Brenda.
{82390}{82435}Dinle, dostum,
{82438}{82497}bu borçlara|büyük bir yük bindirecek.
{82500}{82570}Tony Hawes is nakit aramalarý|nedeniyle çýlgýna dönmüþ durumda.
{82572}{82659}Evet, duyuyorum Brenda. Ama Londra|burada nakit için tek kaynak.
{82662}{82742}Diðer fonlara|giriþimiz yok.
{82784}{82831}Bu þekilde engellemeler çýkarsa,
{82834}{82897}bu iþi kesmek zorunda kalacaðým.
{82899}{82947}Hayýr,|Nick, tamam. Sorun yok
{82951}{83061}Sadece biraz anlamlý|rakamlar çýksýn tamam mý?
{83064}{83109}S. Ktir git.
{83277}{83322}Alo?
{83325}{83370}Nick, tanrýya þükür|seni yakaladým.
{83373}{83440}Dinle, Brenda biraz|zorluyor farkýndayým.
{83443}{83511}Burada iþlerin nasýl|yürüdüðünü bile bilmiyorsunuz.
{83514}{83579}Evet haklý olabilirsin|dostum. Ayarlandý bil.
{83582}{83659}Ancak þu iþlemleri|artýk azaltmaya baþlaman gerekiyor.
{83662}{83731}Bak, Ron,|Ne yapabileceðime bakacaðým, tamam mý?
{83735}{83804}Bu arada,|bonusla ilgili-
{83804}{83864}bütçe çok dar|ve sen istisnasýn,
{83868}{83914}pek fazla deðil maalesef.
{83918}{83966}Yýlýn baþarýlý|geçtiðini sanýyordum!
{83970}{84031}Evet, bu yüzden zaten,|Peter'la özel olarak görüþtüm,
{84034}{84079}ve 350'ye çýkardý.
{84082}{84124}350 mi? Bu saçmalýk.
{84127}{84192}Oldukça uðraþtým.|Ve bu bir istisna.
{84195}{84251}Dinle,|Burada ölesiye çalýþýyorum.
{84254}{84299}SIMEX'in zirvesine taþýdým sizi.
{84302}{84357}Þu yapýlan iþle ilgili|ödül bile geldi.
{84357}{84416}Evet biliyorum, Nick.
{84419}{84466}Dinle,|bakayým ne yapabileceðim.
{84469}{84537}Sanýrým 4'le|baþlamasý gerekiyor, ha?
{84589}{84664}Bu açýlýþ teklifiydi.
{84668}{84741}Eðer hemen kabul etseydim|bir þeylerin yanlýþ gittiðini düþüneceklerdi.
{84741}{84804}Evet, piyango|kazanmak gibi.
{84807}{84869}Seni düþünmeliler.
{84999}{85049}Sorun nedir,|Lisa?
{85052}{85120}Ne olduðunu sanýyorsun, Nick?
{85123}{85192}Her þey deðiþti.
{85194}{85276}Eve gitmek istiyorum.|Bu kahrolasý yerden gitmek istiyorum.
{85279}{85355}Ama sen geri gelmek istemiþtin.|Bonus'a ne oldu?
{85358}{85425}Neden bonusu Londra'da|alamýyorsun?
{85427}{85502}Lütfen, Nick,|Hayatýma devam etmek istiyorum.
{85506}{85605}- Bir aile kurmak istiyorum.|Burada tel baþýma delireceðim.|- Pekala.
{85605}{85666}Sakin ol. Bak,|Sadece biraz zamana ihtiyacým var...
{85669}{85714}bir þeyleri düzene|sokmam gerek.
{85717}{85828}Hayýr sürekli çalýþýyorsun|gece geldiðinde de yataða çöküyorsun.
{85831}{85912}Eðer birlikte olmazsak|nasýl tekrar hamile kalabilirim?
{85915}{86011}Biliyorum ama bir süre|idare etmemiz gerek.
{86013}{86131}- Bonus ne zaman verilecek?|- 25 Þubat'ta.|Beþ hafta var.
{86135}{86201}Tamam 25'inde|uçakta olacaðýz.
{86201}{86283}Ciddiyim. Ýþçileri|yarýn çaðýracaðým.
{86286}{86331}Tamam.
{86358}{86420}Tamam.
{86423}{86475}Bunca þeyin arasýnda,
{86478}{86547}Taciz davasýný|tamamen unutmuþtum.
{86550}{86642}Mahkemeden çýktýðýmda da,|hapse girmem büyük olasýlýktý.
{86803}{86872}Suçlama düþürüldü.
{86875}{86944}200 Dolarlýk bir ceza ödeyeceksiniz.
{86944}{87028}- Temyize de gidebiliriz.|- Çok teþekkür ederim.
{87032}{87104}Çok aptalcaydý.|Tekrar yakayý sýyýrmýþtým.
{87108}{87156}Singapur adalet sistemine.
{87160}{87216}- Özgür dünyaya parýldayan bir örnek.|- Kesinlikle.
{87219}{87281}Barings'e her þeyi açýkça gösterdik.
{87284}{87395}Bundan sonra|bonolar tavana vuracak.
{87398}{87479}Bu arada borsadan bahsetmiþken.|Alo. Anonim teþhirciler.
{87482}{87528}Ben Coopers ve Lybrand'dan Wei Wei.
{87531}{87586}- Nick'le mi görüþüyorum?|- Benim.
{87589}{87634}Yýl sonu kontrollerini|yapýyordum,
{87637}{87697}ve hesaplarda büyük bir|açýk gözüküyor.
{87699}{87832}7.78 milyar yen'i bulamýyorum,|SIMEX'ten gözüküyor.
{87927}{87979}Nick? Beni duyuyor musun?
{87982}{88045}Her þey yolunda mý?
{88048}{88121}Durum biraz karýþýk.|Sorun nedir?
{88124}{88232}Herhangi bir belge bulamadým.
{88235}{88328}Speer, Leads & Kellagg|ve Barings, Londra arasýnda bir anlaþmaydý.
{88331}{88376}Bilgisayarda gözükmüyor|olabilir.
{88378}{88430}Sistem yöneticisiyle görüþüp|size geri dönerim.
{88430}{88520}Üçe çeþit belgeye ihtiyacým var.|Bir: S.L. K'den onay kaðýdý...
{88523}{88594}7.78 milyar ödendiðine dair.
{88597}{88676}Ýki: Parayý aldýðýnýza dair|banka denge belgesi.
{88679}{88726}Ve üç: Ron Baker'dan...
{88729}{88808}anlaþmayý onayladýðýna|dair bir belge.
{88864}{88962}- Ne oldu?|- Önemli deðil.|Sadece bir bilgisayar hatasý.
{88962}{89026}Yýllýk olaðan kontroller.
{91044}{91089}Küçük oyunlarla,
{91092}{91187}havadan 78 milyon dolar|yaratmýþtým.
{91187}{91275}Bu kalpazanlýktý,|açýk ve seçik bir biçimde,
{91278}{91335}ve geri dönüþü de yoktu.
{91335}{91380}- Nick.|- Simon.
{91383}{91444}Tanrým kalp krizi geçiriyordum.
{91447}{91546}- Þu kayýp yedi milyar yen nedir?|- Bir kabus
{91549}{91613}Geçen aydan bir anlaþma|yanlýþ kaydedilmiþ.
{91616}{91661}Bu konuda tepemdeler.
{91664}{91737}Baþýmý aðrýtýyor,|ama ayarlayacaðým.
{91740}{91835}- Ýþin aslý,|Bu parayý bize S.L.K. Borçlu|- S.L.K. De ne?
{91839}{91890}Speer, Leads & Kellagg.|Komisyon þirketi.
{91893}{91954}Bu konuda bilgi istiyorum.
{91958}{92003}Þu adamlarý|tepemden çek.
{92006}{92086}Tabii ki, Simon.|Üzülme, toparlýyorum.
{92194}{92267}Bonnie, ben Nick.
{92270}{92315}Dinle.|Dikkatlice dinlemeni istiyorum.
{92318}{92385}Yarýn ilk iþ olarak|müþteri hesabýndan...
{92388}{92461}bizim hesabýmýza|7.78 milyar yen transfer etmeni istiyorum.
{92461}{92546}Yapamayýz ki.|O kadar para yok.
{92550}{92618}Evet biliyorum. Ancak|hemen sonra geri çevirebilirsin.
{92621}{92709}Sadece elektronik olarak gözükecek.|Transfer yapýlsýn,
{92712}{92769}ve banka bize alýndý|faksý yollasýn...
{92773}{92852}7.78 milyarlýk|krediyi göstersin, tamam mý?
{92899}{92992}- Tamam, Nick. Öyle diyorsan.|- Tamam. Sevgiler, Bonnie.
{93039}{93084}Nick?
{93087}{93148}Þu 7 milyarlýk olay nedir?
{93151}{93220}Londra'dan Tony Hawes aradý.|Seni arýyor.
{93223}{93310}Tanrým, þu yedi milyar|lafýný bir daha duyarsam-
{93313}{93364}70 milyon dolar ediyor,|deðil mi?
{93367}{93415}Hangisi olsun?|Kýrmýzý mý mavi mi?
{93419}{93488}Ne, benim 70 Milyon'u|cebe indirdiðimi mi düþünüyorsun?
{93491}{93574}- Hayýr, öyle bir þey demedim.|- Bilgisayar hatasý.
{93577}{93633}Ofiste yardým için|birisine ihtiyacýn olacak.
{93633}{93702}Sana bunu söylemeye çalýþýyordum.|Sen Süpermen deðilsin.
{93705}{93805}- Baþlama yine þu laflara.|- Orada olsaydým bunlar olmazdý.
{93805}{93871}Doðru. Ben dýþarý çýkýyorum.
{93874}{93934}- Nereye gidiyorsun?|- Sarhoþ olmaya.
{93937}{94002}Eðer birisi ararsa onlara,|Güney Amerika'ya kaçtýðýmý söyle.
{94005}{94067}Sonsuza dek orada kal o zaman!
{94070}{94115}Pislik!
{95160}{95221}Þimdi ne yaptýn,|Leeson?
{95224}{95275}Þimdi ne yaptýn?
{95741}{95810}Gelsene.
{95987}{96032}Kontrol iþinin hallolduðunu|bilmek istersin diye düþündüm.
{96034}{96085}Nick belgeleri ulaþtýrmýþ.|Herkes memnun.
{96088}{96131}Saðol, Ron.
{96134}{96197}Teknik olarak, SIMEX|kurallarýný çiðniyoruz,
{96199}{96259}ancak aslen, yanlýþ anlaþýlmadan ibaret.
{96262}{96330}Büyük ihtimalle de|kontrolörler raporda bundan bahsetmezler,
{96333}{96396}o zaman da|yerel düzenlemeyi ayarlamamýz gerek.
{96399}{96458}Uygun gözüküyor.
{96461}{96591}Biliyor muydun? Nick bir haftada|arbitraj yoluyla 10 Milyon dolar kazanmýþ.
{96595}{96656}Bu yaklaþýk olarak...|yýlda bir milyar dolar ediyor.
{96656}{96705}Adam iþini iyi biliyor.
{96709}{96806}Madem bu kadar iyi iþ yapýyor,|hem de kýsýtlý imkanlarla,
{96808}{96872}Neden bankanýn geri kalanýný|kapatmýyoruz o zaman?
{96875}{96939}- Buna ne dersin?|- Evet.
{97191}{97240}- Alo?|- Nick.
{97243}{97313}Benden mi kaçýyorsun?|Günlerdir sana ulaþmaya çalýþýyorum.
{97316}{97369}Üzgünüm, Tony.|Burasý tam bir karmaþa.
{97373}{97425}Kontroller falan.|Biliyorsun sanýyordum.
{97425}{97468}Þu S.L.K. Olayý.
{97471}{97559}- Her þey temizlendi.|- Biliyorum.
{97562}{97625}Beni rahatsýz eden|bütün parayý nereden buldun?
{97628}{97685}S.L.K.'ye neden ödeme yapmadýn?
{97688}{97746}Yani yaklaþýk|78 milyon dolar ediyor.
{97749}{97805}Birbirini tutmuyor.
{97846}{97891}Çok bariz, Tony.|Fonun bir parçasý...
{97894}{97948}son bir kaç haftadýr|onu kullanýyoruz.
{97951}{98067}- Evet.|- Yani ayný miktar|sana geri gelecek.
{98070}{98178}Anladým. Fonun bir kýsmý|S.L.K.'ye ödenmiþti diyorsun.
{98182}{98272}Aynen öyle, Tony.|Bu þekilde sana geri ödeyeceðiz.
{98275}{98351}O zaman iyi.|Fonu geri almak iyi olacak.
{98353}{98405}Baya sýkýþmýþ|durumdayým.
{98405}{98451}Ýnan bana hepimiz ayný durumdayýz.|Bak, Dinle beni.
{98454}{98505}Kaçmak zorundayým.|Yemekte bir konuðum var.
{98508}{98577}Tabii ki. Þey, sað ol, Nick.
{98580}{98629}Açýða kavuþturduðun için teþekkürler.
{98798}{98843}Evet, Ron.|Ne istiyorsun?
{98846}{98912}Benim; seni pislik, Danny.
{98914}{99007}Bubble? Gecenin bir yarýsý|ne diye aradýn beni?
{99007}{99051}Televizyona yakýn mýsýn?
{99054}{99108}CNN'i açmaný öneririm.
{99226}{99312}En çok hasar gören|yerler Kobe'deki sahil kenarýnda oluþtu.
{99315}{99369}Otoyollar ve demiryollarý|ise parçalandý,
{99372}{99428}- binalarýn çökmesinin|ardýndan ise yangýnlar baþladý.|- Tanrým, deprem.
{99430}{99498}Ýhtiyacýmýz olan buydu.
{99501}{99556}Bu borsayý|öldürür adamým.
{99559}{99623}- Nikkei bununla yerin dibine geçecek.|- Binlerce insan ise...
{99626}{99681}çaresizce kurtarýlmayý|bekliyor.
{99684}{99794}Kurtarma çalýþmalarý ise|zorlukla sürdürülüyor.
{99798}{99882}Mike Chanoi, CNN,|Tokyo'dan bildiriyor.
{100443}{100540}Borsa deli gibi düþtü|sense inanýlmaz sakinsin.
{100544}{100594}Bana göre,|bu bulunmaz bir fýrsat.
{100598}{100647}Nasýl ortalýðý karýþtýracaðým.|Ýzle beni.
{100651}{100721}19.000'e kadar|geri alýn!
{100822}{100899}Senin hakkýnda|söyledikleri ne kadar da doðruymuþ.
{100926}{100997}Ne demek istediðimi anlýyor musun?
{101000}{101076}Tokyo'dan Fernando'yu aramam gerekiyor.|Neyin sallandýðýný görüyor musun?
{101079}{101138}Söz oyunu yapmýyorum.|Fernando, Ben Nick.
{101141}{101186}Kobe'de durum nedir?
{101189}{101282}Baðlantýlarýmýza bir türlü|ulaþamýyoruz.
{101285}{101330}Bir dakika bekle.|Bir þeyler oluyor.
{101334}{101414}Tanrým, satýlýyor!|Satýþ baþladý!
{101418}{101487}Ýnanamýyorum,|bu ne böyle.
{101489}{101566}Hiç bu kadar hýzlý hareket ettiðini görmedim.
{101569}{101673}Üç yüz elli!|Üç yüz elli!|Üç yüz elli!
{101968}{102013}Nick?
{102016}{102086}Kalmamýzý istemediðinden|emin misin?
{102089}{102157}Hayýr, iyiyim, gidin.
{102161}{102206}Yapacaksýn,|Nick.
{102209}{102264}Sana güveniyoruz.
{103103}{103153}Elli milyon.
{103250}{103349}Ben, Nicholas Leeson,
{103352}{103469}bir günde...
{103472}{103538}50 milyon kaybettim!
{103670}{103760}Tam olarak ne yapýyor?|Henüz anlayan yok.
{103764}{103871}Çok basit, Tony. Osama ve SIMEX|arasýnda kontrat deðiþimi yapýyor,
{103875}{103947}iki pazar arasýndaki|fiyat farklarýný istismar ediyor.
{103950}{104015}Bu þekilde müþterilere|en iyi anlaþmalarý sunuyor.
{104018}{104075}Eðer bu kadar kolaysa,|neden herkes öyle yapmýyor?
{104078}{104134}Çünkü bilgi eðrisini|tam ortasýnda bulunuyor,
{104136}{104198}Her þey orada bitiyor.
{104201}{104288}Para yapmanýn|yeni bir yolunu keþfetti.
{104291}{104399}Bize büyük fonlar açtýrmak|konusunda sorunu yok onu biliyorum.
{104438}{104526}Ýþleri kitabýna göre yapmýyor, Ron.|Kurallara uymuyor.
{104529}{104620}Sence Barings'e uygun bir|çalýþan mý?
{104623}{104670}Kurallarý boþ ver, Tony.
{104674}{104749}Londra Nick gibi|insanlar sayesinde deðiþecek.
{104752}{104851}Modern bir finans merkezini|yaþlý moruklarla idare edemezsin.
{104926}{105015}Kahretsin.
{105018}{105063}Uyan bakalým.
{105092}{105144}- Hareket nedir, dostum?|- Sen bana söyle.
{105144}{105223}Bir yukarý çýkýyor,|bir düþüyor...
{105226}{105293}- Daha kötü olmaz bence.|- Kim bilir? Haklý olabilirsin.
{105296}{105357}Sadece bir his tabii.
{105361}{105411}Dinle, dün gece þu Loy denen|adamla birlikteydim-
{105415}{105467}biliyorsun Reuters'deki adam.
{105470}{105568}Gizemli müþteri olmadýðýna|ikna ettim. Senin olduðunu sanýyor.
{105571}{105634}Kendi hesabýndan|bankanýn onayý olmadan...
{105637}{105715}oynadýðýný düþünüyor.
{105718}{105783}O kadar deli deðilsin,|deðil mi?
{105786}{105832}Senin görüþün ne?
{105835}{105880}Peki, kim o zaman?|Beaumarchais?
{105883}{105937}- Sanýrým seni kafaladý.|- Sana söyleyemem.
{105937}{105999}Hadi ama.|Bana da söylemeyecek misin?
{106002}{106078}Sana gösterirsem|sonra seni vurmam gerekir.
{106159}{106223}Bir þeyden eminim.|Eðer müþteri yoksa,
{106227}{106276}onu sen yaratýrsýn.
{106333}{106408}45 milyon mu?|Bu hafta neredeyse 100'ü buldun.
{106411}{106457}Herkes müþteri|operasyonlarýndan sonra...
{106460}{106507}SIMEX'ten acil|telefonlar aldý.
{106510}{106591}Borsanýn dengesizleþeceðinden|korkuyorlar.
{106594}{106671}- Acil mi bu durum?|- Evet.
{106674}{106723}Orada herkes|baðrýþmýyor mu?
{106726}{106780}Hayýr, borsa sakinleþtikten|sonra çýktýk.
{106823}{106929}Nick, daha kaç kere söylemem gerekiyor|þu pozisyonlarý düþür diye?
{106932}{107025}- Buradakiler kafayý sýyýracaklar.|- Orada olduðunu bilmiyordum.
{107028}{107113}Tanrý aþkýna, Uluslararasý|Anlaþmalar Bankasý'na...
{107116}{107179}Barings'in pay ödemelerini|yapamayacaðýný mý söyleyeceðiz.
{107182}{107227}Ýmajýmýz için|iyi olmaz bu.
{107230}{107275}Seni duyuyorum, Ron.|Burasý oldukça sýký.
{107278}{107344}Öyleyse,|o zaman gerçekten çabalaman gerekecek.
{107347}{107392}Zorunda kalýrsan|biraz çarpýt.
{107395}{107497}Norris seninle bunu|konuþacaktýr. Oraya geliyor
{107500}{107545}Norris mi?
{107548}{107593}Geleceðini bilmiyordum.
{107596}{107670}Tony Hawes'la birlikte geliyor.|Bazý kontroller yapmak istiyor,
{107673}{107740}þu fon açma problemlerini|sonsuza kadar bitirmek için.
{107894}{107950}Borsa düþmeden|pozisyonlarýmý...
{107950}{108009}düþürmenin imkaný yoktu.
{108012}{108074}Singapuar'a geldiklerinde|daha da beter durumdaydým,
{108077}{108125}Brenda'dan günlük...
{108128}{108203}30, 40 milyon dolar|istiyordum.
{108206}{108260}Beni öldüreceklerdi.
{108824}{108883}Kötü görünüyorsun, Nick.
{108914}{108974}Berbat görünüyorsun|dostum.
{109155}{109204}- Ýyi akþamlar efendim.|- Ýyi akþamlar.
{109480}{109525}- Nick, iþte buradasýn.|- Özür dilerim geç kaldým.
{109528}{109573}- Merhaba. Sizi gördüðüme sevindim.|- Nick.
{109576}{109627}- Ne içersin?|- Bira alayým, teþekkürler.
{109630}{109690}Bir tane daha lütfen.
{109693}{109738}Nick.
{109789}{109891}- Bugünkü durum nasýldý?|- 18 ve 18.3 arasýnda seyretti,|ufak oynamalar vardý tabii.
{109894}{109939}Deprem sonrasýnda|iþler sakinleþti yani.
{109942}{109987}Yürüttüðün pozisyonlardan,|memnun musun?
{109989}{110059}Rahatladým. Genelde Mart kontratlarý|var, tarihlerinin geçmesini bekliyorum.
{110059}{110107}- Güzel.|- Teþekkürler.
{110107}{110153}Teþekkürler.
{110153}{110236}Þimdi þu sorunlara gelelim...|fon açma meselesi.
{110239}{110338}Brenda Granger Japonya'nýn|tamamýndan senin için borç aldýðýný söyledi.
{110340}{110398}Ýnsanlar konuþmaya baþladý.
{110401}{110450}Anlýyorum.
{110453}{110498}Kesinlikle anlýyorum.
{110501}{110556}Harika.
{110559}{110604}Süpersin.
{110667}{110719}Ve iþte buydu.
{110722}{110795}Bu büyük miktarla|ilgili söyleyeceði þeyler...
{110798}{110867}bundan ibaretti. Barings'deki|rahatsýzlýk bundan ibaretti.
{110870}{110939}Londra'dakilerden|daha iyi olduðu kesin.
{110942}{110988}Bundan sonrakine|bayýlacaksýn.
{110991}{111092}- Istakoz alýr mýydýnýz?|- Hayýr, teþekkürler. Çok aç deðilim.
{111095}{111165}Artýk rahatlamam gerekiyordu,
{111168}{111268}ama 5-8'li hesaptaki|kaybý düþünmeden edemiyordum.
{111271}{111329}Cumartesi günkü|maça kalamaman çok acý.
{111434}{111502}450'ye düþtük deðil mi?
{111533}{111588}Senin bonusun?
{111591}{111636}Bir hafta kaldý.
{111666}{111711}Pardon?
{111714}{111768}Ne yapacaðýný|düþündün mü?
{111772}{111817}Bir hafta kaldý.
{111903}{111976}Affedersiniz.
{111979}{112036}Bir açýklama yapmak istiyorum.
{112065}{112110}Bazýlarýnýz borsadaki...
{112113}{112181}patlamadan endiþelisiniz biliyorum,
{112184}{112244}ve eminim|þu gizemli müþteriyi de...
{112247}{112323}merak ediyorsunuz.
{112326}{112430}Aslýnda,|öyle birisi yok.
{112457}{112526}Müþteri biziz-|Barings.
{112530}{112579}Ve 5-8'li hesaba|dikkatlice bakarsanýz-
{112583}{112653}müþteri hesabý olmadýðýný anlarsýnýz,|burasý bir hata hesabý-
{112657}{112714}kayýplarý gizleyen bir hesap...
{112717}{112793}yaklaþýk|200 milyon'luk bir büyüklüðü var.
{112796}{112891}Hayýr yalan söyledim.|230'a yakýn.
{113103}{113165}Bir hafta kaldý.
{113168}{113266}O kadar parayla|ne yapacaðýný düþündün mü, Nick?
{113434}{113487}Borsaya yatýrým yapmayacaðým kesin.
{113579}{113636}- Bu çok iyiydi.|- Çok iyi
{113812}{113923}Her gün bir|mucize olmasýný bekliyordum.
{113926}{114021}Pozisyonu artýk ben iþletmiyordum,|o beni kontrolüne almýþtý.
{114065}{114141}Þu haline bir bak.|Titriyorsun dostum.
{114145}{114215}- Çok mu içtin?|- Hayýr.
{114219}{114292}- Borsa beni öldürüyor.|- Bana mý söylüyorsun.
{114296}{114349}Ýðrenç durumdayýz.
{114405}{114479}Penguen mi?|Seni þanslý pislik.
{114482}{114589}Ne kadar ender|olduklarýný biliyor musun?
{114680}{114755}- Hiç de komik deðil.|- Þanslý Leeson.
{114758}{114831}Senin olsun.|Sana gülmüyorum, dostum.
{114875}{114936}Kahretsin. Üzgünüm.
{115012}{115064}Gerçekten durumun kötü,|deðil mi?
{115068}{115113}Sorun nedir?
{115180}{115235}Onaylanmamýþ|bir pozisyonum var.
{115333}{115396}Hadi ya.
{115398}{115443}Büyüklüðü nedir?
{115470}{115522}Sorun yaratacak kadar büyük.
{115555}{115600}Zavallý pislik.
{115603}{115691}Buna þaþýrdýðýmý söyleyemeyeceðim|Lisa biliyor mu peki?
{115694}{115739}Hayýr, beni öldürür.
{115743}{115789}Kendi dertleri|ona yeter.
{115789}{115865}Bonus'un verileceði günü bekliyor|eve geri dönmek için.
{115869}{115916}Ne yapacaksýn peki?
{115963}{116009}Satýn almaya devam|edeceðim...
{116012}{116075}sanki borsayý|desteklemek amacýyla yapýlýyormuþ gibi.
{116078}{116143}18,000 civarýnda durursa,|o zaman seçeneklerim hala durur,
{116146}{116202}ve pozisyonu geri alabilirim.
{116205}{116269}- Ve bu iþten kurtulabilirim.|- Nick.
{116272}{116333}Beni dinlemeni istiyorum, tamam mý?|Beni dinle.
{116336}{116384}Borsaya karþý gelme adamým.
{116387}{116471}Pay aramalarýný yapsan bile|kontratýn tarihi geçince ne olacak?
{116474}{116578}Borsanýn þu andaki haline bakarsan|kayýplarýn inanýlmaz boyutlarda olur.
{117207}{117283}Bine beþ!|Bine beþ! Hadi!
{117286}{117334}Hadi, George!|Þunu harekete geçir!
{117338}{117400}Eðer 18,000'in altýna inerse,|biz öldük!
{117577}{117622}Hadi!
{118090}{118151}Nick.
{118155}{118210}- Nick?|- Tony.
{118214}{118300}Nick, Bazý rakamlarýn üstünden|geçmemiz gerekiyor.
{118303}{118351}Olur, Tony.
{118438}{118490}Bir dakika içinde dönerim.
{118566}{118617}Düþüyor, Nick.
{118620}{118697}- Deli gibi düþüyor.|- Hadi!
{118811}{118856}Özür dilerim! Para!
{120027}{120072}Milyonlarý ortalýða savurdum,
{120075}{120127}ama hiçbir þey deðiþmedi.
{120130}{120196}Bonus verilmesine|bir gün kalmýþtý,
{120198}{120252}ama oyun bitmiþti.
{120255}{120300}Yenilmiþtim.
{121235}{121314}Nick sen bir aptalsýn,|biliyor musun?
{121317}{121362}Þey, bu dünyanýn|sonu deðil.
{121366}{121423}Saðlýklýsýn,|ben varým.
{121451}{121500}Bonus'u boþver.
{121504}{121565}Üzgünüm.
{121565}{121626}Yavaþla biraz.|Video dükkaný hemen solda.
{121629}{121683}- Gidip depozitomuzu feri alacaðým.|- Tamam.
{121686}{121735}Ýhtiyacýmýz olacak,|hayatým.
{122108}{122155}- Alo?|- Tanrý aþkýna.
{122158}{122212}Pozisyonlar giderek büyüyor.|Eðer düþmezse,
{122216}{122273}oraya gelip|seni ben düzelteceðim.
{122277}{122359}- Sesin kýsýk, Ron.|- Þu ortamdaki dedikodu nedir peki?
{122362}{122408}Müþterinin biz|olduðumuza dair bir söylenti var.
{122411}{122461}Özür dilerim, Ron,|daha yüksek konuþ.
{122464}{122523}Bizim müþteri|olmadýðýmýzý söyle, Nick.
{122526}{122600}- Sesin gidip geliyor, Ron.|- Nick- Nick, orada mýsýn?
{122603}{122667}Hoþça kal, Ron.
{122744}{122789}200'ðn tamamýný vermek istemediler,
{122792}{122837}ancak 180 koparabildim.
{122840}{122885}Süpersin.
{122967}{123057}Nick?
{123713}{123778}Özür dilerim bayým.|Size bir telefon var.
{123781}{123852}- Þimdi deðil.|- Arayan Peter Norris.|Acil olduðunu söyledi.
{123856}{123941}Teþekkürler.|Ýzin verir misiniz?
{124186}{124231}Peter?
{124234}{124305}Partinden alýkoyduðum|için özür dilerim.
{124334}{124401}Korkarým bazý|kötü haberlerim var.
{124463}{124531}Londra'dakiler olayý anladýðý zaman,
{124534}{124649}biz çoktan Singapur'dan uzaklaþmýþtýk,|artýk geleceði düþünmek gerekiyordu
{124652}{124697}eðer öyle bir þey kaldýysa.
{124724}{124798}Ne olacak,|Nick?
{124801}{124884}Faksýmý alýp Cuma günü|bütün pozisyonlarý kapatýþ olmalarý gerek.
{124887}{124941}Borsa bu iþi|kaldýrýr.
{124944}{124999}Ama artýk tamamen|iþsiz kaldýn?
{125070}{125163}Daha kötüsü olabilirdi,|zaten tonlarca para kaybettirdim.
{125232}{125289}Açlýktan ölüyorum.|Burada hamburger var mýdýr?
{125292}{125341}Hayýr hamburger yemeni istemiyorum.
{125345}{125434}- Þu açlýðýn beni delirtecek.|- Beni sinirlendirme genç bayan.
{125437}{125513}Ben de spor salonuna gideyim bari.
{125597}{125642}Öyle kal-
{125799}{125897}- Dursana. Ýnsanlar bakýyor.|- Ne olmuþ? Umurumda deðil,|gel bakalým buraya.
{126025}{126074}Tanrým, Lisa.
{126111}{126157}Barings iflas etmiþ.
{126160}{126220}Net?
{126224}{126275}Maliye bakaný,|Kenneth Clarke,
{126279}{126367}Barings Bank olayýndan doðan|gerilimi azaltmaya çalýþýyor.
{126370}{126435}Meclisteki konuþmasýnda,|Ýngiliz banka sisteminin...
{126435}{126494}çöktüðüne dair|söylentileri yalanladý.
{126496}{126595}Baring'in baþarýsýzlýðýnýn|kendi sorunlarý olduðunu söyledi...
{126598}{126686}bunun nedeni de|Singapur'daki sahtekar bir çalýþanmýþ.
{126689}{126757}800 Milyon ila|bir milyar pound...
{126757}{126824}arasýnda bir kayýp olduðu varsayýlýyor.
{126827}{126931}Borsa Pazartesi günü buna nasýl|tepki gösterecek bilinmiyor.
{126934}{127013}Ýngiltere Bankasý durumu kurtarmak|için bir kurtarma paketi hazýrlýyor-
{127017}{127101}Brunei Sultan'ýnýn da|bankayý satýn almak istediði söyleniyor-
{127104}{127222}Ýngiltere'nin en köklü ve güçlü|finansal þirketi zor durumda.
{127225}{127318}- Charles Samson, CNN, Londra.|- Kahretsin.
{127356}{127401}Nick.
{127548}{127602}Nasýl bana söylemezsin?
{127605}{127690}Bunca zaman neden|benden sakladýn, Nick?
{127748}{127802}Tanrým sen cehennemi yaþamýþsýn.
{127805}{127918}- Beni Simon Jones'un ofisine yollardýn.|- Kesinlikle yapardým.
{127921}{128008}Sonra kovulurdum,|ve parayý geri kazanma|þansým da olmazdý.
{128011}{128086}- Yapacaðým buydu.|- Hayýr kumar oynuyordun.
{128088}{128171}Hem de baþkalarýnýn parasýyla.
{128206}{128274}Sizi yüzüstü|býrakmak istemedim-
{128302}{128354}seni, babamý
{128358}{128418}ofisteki kýzlarý,
{128453}{128515}hatta lanet Ron Baker'ý bile.
{128592}{128659}Þimdi benden nefret mi edecekler?
{128662}{128739}Pek popüler olmayacaðýn çok açýk.
{128815}{128901}Baþka yollarý da vardý, biliyorsun.
{128904}{128955}Ama çok yakýndýk.
{128998}{129054}Sonra bir kahraman olacaktým.
{129098}{129169}Gel buraya.
{129173}{129218}Gel buraya.
{129295}{129377}Hala seni çok seviyorum?
{129380}{129456}- Çok seviyorum.|- Ben de seni seviyorum.
{129652}{129742}Þu göbekle ilgili|bir þey yapabilir miyiz?
{129745}{129790}Anlýyorum.
{129827}{129873}Evet, anlýyorum.
{129877}{129939}Hayýr tabii ki deðil.
{129943}{130036}Ýlginiz için|tekrar teþekkürler. Hoþça kalýn.
{130126}{130170}Brunei Sultan'ýnýn|ofisinden aradýlar.
{130172}{130217}Ýþlem yapmamaya|karar vermiþler.
{130220}{130282}Risklerin çok büyük olduðunu|ve zamanýn da kýsa olduðunu söylediler,
{130285}{130330}Uzak Doðu'da uzun süre...
{130333}{130430}yeterli destek olmadan|bir þey yapýlamayacaðýný belirtti.
{130433}{130493}Baþka kimse yok mu?
{130496}{130602}Herkesi denedik.|Umutsuz durumdayýz.
{130605}{130713}Barings'in iflasýný|resmen açýklayalým...
{130717}{130779}sonra da likidasyona gidelim.
{130940}{131047}Peter Barings televizyona çýktý|ve bunun bir komplo olduðunu söyledi.
{131050}{131095}800 milyon'luk bir kayýptan bahsetti!
{131098}{131159}Benim kaybým o kadar çok deðildi.|300 civarýnda olmasý gerekiyor.
{131159}{131206}Ama Barings|Cuma günü bir þey yapmadý.
{131209}{131295}- Açýklamanýn ardýndan,|borsa da patladý.|- Salak herifler!
{131295}{131379}- Þu an yatýmýzda|keyif yaptýðýmýzý düþünüyorlar.|- Ne?
{131382}{131431}Biliyorum.|Ama dinle dostum,
{131434}{131500}burada artýk dostun yok,|O yüzden Asya'dan hemen kaç.
{131504}{131580}Londra, Avustralya,|neresi olursa olsun git.
{131584}{131652}- Buna uðraþýyoruz.|- Bu arada, Nick,
{131655}{131700}iyi bir avukat bul.
{131703}{131775}- Ýyi þanslar.|- Sevgiler, dostum.
{131778}{131896}187 sayýlý Hong Kong uçaðý|iki numaralý kapýdan ayrýlýyor.
{131899}{131966}Kahretsin.
{131993}{132038}Kahretsin.
{132167}{132224}Bu delilik.|Asya'ný her yerinde seni arýyorlar.
{132227}{132285}Endonezya civarýnda|senin yatýnda geziyoruz sanýyorlar.
{132285}{132357}- Ne yatý be?|- Biliyorum.|Uçuþlardan ne haber?
{132361}{132440}- Singapur üzerinden|Londra'ya giden bir uçuþ var.|- Bu iyi deðil.
{132443}{132519}Abu Dhabi üzerinden Frankfurt'a var.
{132522}{132627}Onu alalým.|Ve Lisa, nakit öde.
{132803}{132920}Malezya Havayollarý,|7682 sayýlý Frankfurt uçaðý...
{132923}{132968}kalkýþa hazýrdýr.
{132971}{133042}Yolcular lütfen çýkýþ|kapýlarýna yönelsinler.
{133045}{133088}Teþekkürler.
{133859}{133904}- Gazete ister misiniz?|- Hayýr, teþekkürler.
{133907}{133952}- Bayan?|- Hayýr, teþekkürler.
{133955}{134014}Abu Dhabi yoluyla|Frankfurt, Almanya uçuþuna hoþ geldiniz.
{134018}{134092}- Yüksekliðimiz yaklaþýk olarak-|- Nick, þunu çýkarsana.
{134095}{134173}- Þuradaki adam bana bakýyor.|- Öyle mi?
{134175}{134222}Bu lanet þapkayla|bakmasa þaþardým.
{134225}{134322}Ýlgi çekmek istemiyorsan.|Böyle salakça gözükme.
{134325}{134380}Sizlere hatýrlatmak istiyoruz|sigara içmek-
{134383}{134441}Abu Dhabi'de|duracak mýyýz peki?
{134444}{134496}Evet.
{134499}{134551}Lisa, orada|insanlarýn elerini kesiyorlar.
{134554}{134617}Saçmalama.
{134620}{134665}Sadece taþlarlar.
{134699}{134752}Ne?
{134755}{134813}Özür dilerim,|ama gülmen gerekiyordu.
{134816}{134897}Zavallý yaþlý Barings.
{134901}{134970}Yanlýþ insaný|iþe alýrsan böyle olur.
{135339}{135400}O zaman yaptýðým-
{135400}{135476}þeyin büyüklüðünü anladým.
{135480}{135562}Ne olursa olsun,|yine ayný þeyler olacaktý.
{135562}{135642}Hayatým boyunca|hiç yalnýz hissetmedim.
{135863}{135918}Seni seviyorum, Lisa.
{135921}{135985}Ne olursa olsun,|Seni seviyorum.
{135988}{136037}Ben de seni seviyorum.
{136064}{136126}Londra'ya geri|dönmemiz gerekiyordu.
{136129}{136176}Singapur'da hapiste|olsam buna dayanamazdým.
{136179}{136246}Seni görmemeye|dayanamazdým.
{136390}{136439}Tanrým, polis gelmiþ.
{136443}{136494}Burada olduðumu|öðrenmiþ olmalýlar.
{136497}{136574}Öyle olmamasý,|gerekiyor.
{136577}{136635}Uçuþ erken olduðu için,
{136638}{136713}pasaport kontrolü|sen uçaðý terk ettikten sonra olur.
{136716}{136766}Lütfen evraklarýnýzý hazýrlayýn.
{136769}{136829}Gördün mü?
{136917}{136972}Korkuyorum, Lisa.
{137006}{137064}Güçlü ol, tamam mý?
{137249}{137294}Teþekkürler.
{137322}{137365}Geçin, rica ederim.
{137368}{137482}Teþekkürler.
{137485}{137544}Pasaportunuza bakabilir miyim?
{137611}{137656}Kocanýz nerede?
{137703}{137748}Ben kocasýyým.
{138182}{138288}Beþte yirmi! Beþte yirmi!|Beþte yirmi!
{138291}{138376}100'e 250 ver!|100'e 250 ver! Hadi!
{138376}{138426}Kim istiyor?|100'e 250 ver!
{138429}{138491}100'e 250 ver!|Hadi!
{138921}{138971}Tama bu kadar yeter.
{138974}{139029}Hikayem burada bitiyor.
{139065}{139121}Barings bir Alman|bankasýna satýldý...
{139124}{139198}inanýlmaz ucuz bir fiyata.
{139238}{139333}Lisa uçuþ görevlisi|olarak yeni bir hayata baþladý.
{139336}{139381}Duyduðuma göre|yeni birisini bulmuþ.
{139451}{139533}Bana gelince baþarýsýz bir biçimde
{139536}{139668}Frankfurt'tan Singapur'a|gönderildim ve kalpazanlýktan.
{139704}{139780}Altý buçuk yýl|hapse mahkum oldum.
{139814}{139887}Gizli banka hesaplarý söylentilerine raðmen.
{139890}{139981}Bu sahtekarlýktan|hiç bir kazancým olmadý.
{140017}{140122}Dürüst olmak gerekirse,|keþke bir þeyler kazansaydým.
{140162}{140562}Downloaded From www.AllSubs.org

