{1}{1}23.976 / Petr Medek
{2113}{2178}DÍKY!
{2279}{2314}Hlavou se mi honí myšlenky.
{2319}{2385}Je svatého Valentına 2004.
{2420}{2494}Tenhle svátek vymysleli|obchodníci s pohlednicemi,
{2517}{2584}aby se lidi cítili mizernì.
{2662}{2702}Dnes jsem nešel do práce.
{2765}{2810}Jel jsem vlakem do Montauku.
{2870}{2913}Ani nevím proè.
{2955}{3004}Nebıvám impulsivní.
{3188}{3252}Nejspíš jsem dnes|vstal levou nohou.
{3276}{3324}Musím si dát opravit auto.
{3332}{3366}Ahoj, Cindy.
{3367}{3395}Tady je Joel.
{3416}{3447}Joel.
{3448}{3500}Poslyš, dnes mi|nìjak není dobøe.
{3537}{3588}Ne, asi jsem snìdl|nìco zkaeného.
{3599}{3656}Na plái je fakt zima.
{3671}{3735}Montauk v únoru,|to byl teda nápad, Joele.
{3797}{3837}Chybí tu stránky.
{3837}{3887}Nevzpomínám si,|e bych je vytrhnul.
{3949}{4029}Vypadá to, e tohle je mùj|první zápis po dvou letech.
{4241}{4283}Lidi písek pøeceòují.
{4304}{4362}Vdy to jsou jen|malinkaté kamínky.
{4594}{4647}Ké bych si tak|našel nìkoho nového.
{4680}{4752}Nadìje, e se to stane,|je bohuel minimální.
{4753}{4851}Ani nejsem schopnı se|podívat cizí enì do oèí.
{4894}{4951}Asi bych se mìl vrátit k Naomi.
{4971}{5007}Byla milá.
{5020}{5059}Milá, to je fajn.
{5106}{5142}Milovala mì.
{6031}{6159}Proè se zamiluju do kadé,|která o mì projeví sebemenší zájem?
{7169}{7193}Ahoj.
{7213}{7237}Pardon?
{7238}{7275}Jen jsem tì pozdravila.
{7277}{7309}Ahoj. Nazdar.
{7351}{7390}Mùu si pøisednout?
{7457}{7485}Kam jedeš?
{7511}{7550}Do Rockville Centra.
{7551}{7591}Nepovídej! Já taky!
{7597}{7660}- Vánì?|- To je teda náhoda.
{7722}{7758}Neznáme se u?
{7842}{7886}Nechodíš do knihkupectví|Barnes a Noble?
{7887}{7919}Jasnì.
{7920}{7957}- Tak odtud!|- Ano.
{7958}{8002}U jsem tì vidìla, èlovìèe.
{8006}{8106}Otroèím tam u... pìt let.
{8120}{8195}- Jeiši, to u je pìt let...|- Nìjak si tì nevybavuju.
{8195}{8214}To urèitì dìlají ty vlasy.
{8232}{8308}- Co dìlají?|- Èasto toti mìním barvu.
{8309}{8358}Proto si mì asi nepamatuješ.
{8370}{8410}- Tahle se jmenuje Modrá troska.|- Vánì?
{8450}{8501}- Dobrı jméno, co?|- Líbí se mi.
{8578}{8658}Mimochodem, barvy spoleènosti,|co ji vyrábí, mají všechny zajímavı jména.
{8676}{8755}Jako Rudá hrozba,|lutá horeèka, Zelená revoluce.
{8779}{8827}To musí bıt skvìlá práce,|vymıšlet tyhle jména.
{8827}{8891}Ty si myslíš, e|takové zamìstnání existuje?
{8899}{8957}Vdy kolik barev mùe|ta spoleènost vyrábìt?
{8967}{8995}Padesát?
{9000}{9046}Nìkdo to dìlat musí.
{9075}{9140}Agent Pomeranè!|Tu jsem vymyslela já.
{9168}{9227}Mìním svojí osobnost|spolu s barvou.
{9234}{9283}O tom bych docela pochyboval.
{9303}{9343}Ani mì neznáš.
{9372}{9415}Neznáš mì, e ne?
{9488}{9583}Promiò.|Jenom jsem se snail bıt milı.
{9615}{9667}Jasnì. Chápu.
{10126}{10180}Mimochodem,|jmenuju se Clementine.
{10186}{10214}Já jsem Joel.
{10214}{10238}Ahoj, Joele.
{10280}{10319}Hlavnì nevtipkuj o mım jménì.
{10319}{10375}Ale ne, to bys ty neudìlal.
{10383}{10423}Snaíš se bıt milı.
{10433}{10484}Neznám ádné vtipy|o tvém jménì.
{10495}{10536}Huckleberry Hound.
{10564}{10605}Netuším, co to znamená.
{10606}{10640}Huckleberry Hound?
{10660}{10725}- Seš normální?|- Nìkdo øíká, e ani moc ne.
{10741}{10829}"Oh my darling, oh my darling,|oh my darling Clementine.
{10829}{10942}You are lost and gone forever,|dreadful sorry, Clementine."
{10950}{10999}- Nic?|- Je mi to líto.
{11025}{11075}Je to krásné jméno.|Vánì hezké.
{11075}{11127}Znamená milosrdnost.
{11128}{11186}Správnì? Clemency?
{11187}{11226}Pro mì se jenom tìko hodí.
{11227}{11283}Jsem pomstychtivá mrcha,|jestli chceš slyšet pravdu.
{11283}{11338}Myslím, e taková nejsi.
{11339}{11382}Proè si myslíš,|e taková nejsem?
{11400}{11439}Já nevím. Jenom...
{11485}{11589}Nevím.|Pøipadáš mi tak milá.
{11590}{11622}Take teï jsem u i já milá?
{11646}{11703}Proboha!|To neznáš ádnı jinı pøídavnı jméno?
{11703}{11740}Nestojím o to.
{11741}{11834}Nestojím o to bıt milá,|ani aby na mì nìkdo byl milı.
{11945}{11975}Joele?
{11995}{12031}Jmenuješ se Joel?
{12066}{12091}Ano.
{12129}{12167}Omlouvám se,|e jsem na tebe køièela.
{12190}{12239}Dneska jsem nìjak mimo.
{12482}{12599}Je to trapné, ale musím se pøiznat, e právì|teï jsem ráda, e se na mì snaíš bıt milı.
{12631}{12692}Teda, tìko øíct,|co si budu myslet za chvíli, ale...
{12700}{12752}právì teï...
{12776}{12812}jsem ráda, e jsi milı.
{13008}{13050}Mám tady nìjakou práci,
{13054}{13088}co musím dodìlat.
{13160}{13198}- Trošku píšu...|- Omlouvám se.
{13208}{13248}- Ne, ne...|- Samozøejmì. To je v poøádku.
{13249}{13300}Chápeš, tohle je...
{13339}{13372}Dávej na sebe bacha.
{13376}{13408}Jeiši!
{13735}{13759}Ahoj!
{13769}{13847}Nechceš svést?
{13873}{13897}Venku je zima.
{13901}{13942}Jo! Fajn, dobøe.
{13943}{13977}Mrzne a praští.
{13981}{14034}Nejseš náhodou uchylák,|co sleduje holky?
{14035}{14097}Ne, nejsem úchylák.|To ty ses zaèala se mnou bavit.
{14097}{14145}To je ta nejstarší finta,|co doporuèují v pøíruèce pro úchyláky.
{14146}{14172}Vánì?
{14179}{14217}Ona je pøíruèka pro úchyláky?
{14273}{14313}Tu bych si mìl pøeèíst.
{14441}{14518}Víš, moná to vypadá,|e jsem trošku divná.
{14523}{14560}Ale to já nejsem.
{14561}{14598}V poøádku.
{14600}{14643}Nemyslel jsem si to o tobì.
{14778}{14814}Nechceš zajít na panáka?
{14842}{14906}Mám spoustu pití, take...
{14962}{14988}Nevadí.
{14989}{15042}Promiò, to bylo hloupé.|Je mi trapnì.
{15043}{15078}- Ne, ale ne...|- Dobrou noc.
{15563}{15611}Dvì Modré trosky.
{15659}{15727}- To je hezké.|- Do dna, mladíku.
{15737}{15812}A to svádìní není tak upjaté.
{15899}{15962}Dìlám si legraci! No tak!
{16120}{16174}Ty toho moc nenamluvíš, co?
{16175}{16244}Promiò, víš...
{16252}{16342}Mùj ivot není tak zajímavı.
{16348}{16383}Chodím do práce
{16384}{16420}a zpátky domù.
{16440}{16474}Není moc o èem vykládat.
{16500}{16552}Mìla by sis pøeèíst mùj deník.
{16554}{16664}Je celı... prázdnı.
{16665}{16717}Vánì?|Nejsi z toho smutnı?
{16717}{16746}Nebo úzkostlivı?
{16748}{16817}Já jsem vdycky úzkostlivá, e neproívám|svùj ivot tak naplno, jak bych mohla.
{16817}{16867}Chápeš, vyuít kadou pøíleitost.
{16868}{16941}Chci si bıt jistá, e nepromarním|jedinou chvilku svıho ivota.
{16957}{17012}- Taky na to myslím.|- Ano?
{17129}{17172}Ty jsi vánì milı.
{17188}{17261}U to nesmím øíkat.
{17300}{17340}Jednou si tì vezmu.
{17343}{17378}Vím to.
{17431}{17457}Dobøe.
{17576}{17600}Joele.
{17613}{17674}Mìl bys se mnou|nìkdy zajet k øece Charles.
{17683}{17726}V tuhle roèní dobu|je celá zamrzlá.
{17730}{17782}- Z toho bìhá mráz po zádech.|- Pøesnì.
{17802}{17842}Udìláme si piknik.
{17851}{17886}Noèní piknik.
{17890}{17958}Zvláštní noèní piknik.
{17974}{18023}To zní hezky.
{18043}{18103}Ale mìl bych u jít.
{18127}{18193}- Mìl bys zùstat.|- Ne, já doopravdy...
{18194}{18218}Já...
{18219}{18294}- Musím brzo vstávat.|- Chtìla bych, abys mi zavolal.
{18301}{18334}Zavoláš mi?
{18341}{18380}Budu ráda.
{18381}{18410}Ano.
{18499}{18566}A budeš volat,|popøej mi šastnıho Valentına.
{18578}{18622}To bude milı.
{19600}{19644}Proè ti to trvalo tak dlouho?
{19652}{19684}Právì jsem pøišel.
{19713}{19757}Chybím ti?
{19789}{19835}Musím pøipustit, e ano.
{19851}{19929}To znamená,|e jsme u svoji.
{19929}{19968}Asi ano.
{19974}{20005}Dnes v noci?
{20006}{20041}Líbánky na ledì?
{20043}{20091}Led je teï vánì pevnı.
{20121}{20175}- Já ti nevím.|- No tak, pojï.
{20190}{20236}Pojï sem.
{20377}{20413}Je tu nádhernì.
{20444}{20477}Je.
{20585}{20625}Nechoï moc daleko!
{20682}{20722}Jsi v poøádku?
{20818}{20866}Au, mùj zadek!
{20906}{20951}- Mìli bychom se vrátit.|- Pojï sem!
{20963}{21001}- Pojï!|- Co kdy se led prolomí?
{21011}{21074}Co kdy?|O to se právì teï staráš?
{21090}{21140}Pojï sem, prosím.
{21314}{21378}Zklouznem se.
{21397}{21424}To je fajn.
{21425}{21474}Nìco ti ukáu.
{21578}{21607}Lehni si.
{21741}{21792}Slyším, jak ten led praská.
{21795}{21849}Ale nepraská.
{21849}{21914}Nemùe se prolomit,|je poøádnì tlustı.
{21967}{22027}Uka mi,|jakı znáš souhvìzdí.
{22099}{22161}ádná neznám.
{22195}{22243}Uka mi, kterı znáš.
{22243}{22285}Dobøe.
{22315}{22343}Dobøe.
{22419}{22459}Támhle je Osidius.
{22460}{22487}Kde?
{22503}{22616}Pøímo támhle.|Ta šmouha a køí.
{22619}{22677}Osidius emfatickı.
{22708}{22748}Kecáš, e jo?
{22748}{22804}Ne.|Osidius je pøímo tam.
{22804}{22849}Šmouha a køí.
{22850}{22911}Neštvi mì.
{23196}{23240}Clementine.
{23248}{23286}Budíèek.
{23405}{23444}Omlouvám se,|e jsem tì probudil.
{23452}{23478}Jsme tu.
{23695}{23750}Mohla bych jet k tobì?
{23786}{23830}Vyspat se.
{23830}{23870}Jsem tak unavená.
{23904}{23975}Dobøe.|Jasnì. Samozøejmì.
{23976}{24011}Skoèím si|pro kartáèek na zuby.
{24570}{24594}Ano?
{24612}{24652}Mùu vám nìjak pomoct?
{24658}{24691}Jak to myslíte?
{24722}{24763}Jestli vám mùu|s nìèím pomoct?
{24802}{24834}Ne.
{24859}{24895}Co tady dìláte?
{24896}{24967}Nejsem si úplnì jistı,|na co se mì to ptáte.
{24988}{25070}Aha, díky.
{26040}{26120}VÌÈNİ SVIT|NEPOSKVRNÌNÉ MYSLI
{27670}{27716}Dùm èíslo 159.
{27717}{27759}Co je tu za èíslo?
{27775}{27886}Proboha, mùeš aspoò|na chvilku posvítit na ty èísla?
{27890}{27935}Asi jo.
{27963}{27987}To je on.
{28353}{28377}Joele.
{28378}{28411}Franku.
{28471}{28515}To je v prdeli.
{28531}{28619}Jediná moje matka mi|poslala pøání k Valentınu.
{28620}{28659}To je k pláèi, co?
{28678}{28766}Ty máš štìstí, máš Clementine.|Ta je fakt skvìlá.
{28772}{28838}Máte dnes na veèer|nìco naplánovaného?
{28929}{28956}Ne.
{28957}{29024}Já jenom, jestli nìkde|nemáte zarezervované místo.
{29025}{29070}Nechcete pøece|skonèit u Mekáèe.
{29078}{29124}McRomantika.
{29128}{29164}Budete chtít|hranolky k tomu shaku?
{29165}{29250}Jdu se teï prospat, Franku.
{29260}{29307}Je teprve pùl deváté.
{29981}{30037}Patricku, nech toho.
{30469}{30508}Dobrı, dobrı.
{30533}{30565}V pohodì.
{30687}{30724}A Apollo mùe vystartovat.
{31374}{31422}Joele.|Jak se máš?
{31456}{31488}Ahoj, Franku.
{31628}{31696}Jediná moje matka mi|poslala pøání k Valentınu.
{31699}{31744}To je k pláèi, co?
{31767}{31820}Ty máš štìstí,|máš Clementine, Joele.
{31828}{31922}Máte dnes na veèer|nìco naplánovaného?
{31944}{31969}Ne.
{31984}{32066}Já jenom, jestli nìkde|nemáte zarezervované místo.
{32072}{32130}Nechcete pøece|skonèit u Mekáèe.
{32165}{32209}- Ne!|- Ano?
{32209}{32281}Vdy za tøi dny je u Valentın,|chtìl jsem to vyøešit.
{32291}{32334}Dát to zase do poøádku.
{32335}{32362}Zkusil jsem jí zavolat,
{32363}{32412}ale ona si zmìnila èíslo.
{32424}{32503}Tak jsem si øekl,|e ji zajdu nìco koupit.
{32504}{32624}e se za ní zastavím v práci.|Dám ji valentinku.
{32628}{32664}Nemùu tomu uvìøit.
{32686}{32769}Byla tam s nìjakım klukem.
{32773}{32833}S takovım mladíèkem.
{32843}{32929}A chovala se ke mnì,|jakoby mì ani neznala.
{32937}{32976}Pøejete si?
{32985}{33034}Hledáte nìco, pane?
{33122}{33213}- Ahoj, Mandarinko.|- Patricku!
{33214}{33258}Mùj chlapeèku.
{33344}{33397}- Co tady dìláš, zlato?|- Chtìl jsem tì pøekvapit.
{33397}{33441}Mohl byste|chvilku poèkat, pane?
{33457}{33490}Ahoj.
{33513}{33537}Jak se máš?
{34034}{34082}Proè mi to udìlala?
{34177}{34223}Dá si nìkdo jointa?
{34238}{34310}Proboha, Robe,|dej s tím na chvilku pokoj.
{34311}{34364}- Snaí se mì potrestat.|- Já vím.
{34365}{34417}- Protoe jsem byl upøímnı.|- Je to hrozné.
{34417}{34462}- Mìl bych za ní zajít.|- Ne, to ne.
{34463}{34498}Nemìl bys tam chodit.
{34499}{34538}Nemìl.
{34559}{34594}- Je to pøíliš...|- Máš pravdu.
{34598}{34650}Nechci, aby mì|vidìla takhle znièeného.
{34657}{34707}Joele, moná bys to|mìl brát jako znamení.
{34715}{34755}Pro klidnı rozchod.
{34895}{34927}Víš co, Joele?
{34928}{34980}- Podívej...|- Robe.
{34981}{35027}- Øeknu ti, jak to je.|- Nedìlej to.
{35028}{35063}Robe, co to dìláš?
{35077}{35123}A co chceš teda dìlat, Carrie?
{35124}{35204}- Jaké je tvé dokonalé øešení?|- Take teï to pøetáèíš na naše problémy?
{35204}{35276}- Tohle ale není o nás.|- Máš pravdu, tohle není o nás, ale o Joelovi.
{35277}{35362}Je dospìlı. U to není|malı chlapeèek mamky Carrie.
{35409}{35435}Co tím sakra...
{35436}{35471}Tohle je stejnì tvoje.
{35507}{35535}To je skvìlı.
{35536}{35568}Fajn.
{35856}{35880}Dobøe.
{35881}{35944}Clementine Kruczynski si nechala|vymazat Joela Barishe z pamìti.
{35945}{36007}U se pøed ní, prosím,|nezmiòujte o jejich vztahu.
{36007}{36049}Dìkujeme, Lacuna Inc.
{36050}{36094}- Co to má sakra bıt?|- Já nevím.
{36097}{36138}Nìjaká spoleènost,|co dìlá takové vìci.
{36448}{36481}Dobré ráno, Lacuna.
{36513}{36597}Ne, omlouvám se, nabídka|platila pouze do konce roku.
{36649}{36718}Samozøejmì,|mohli bychom vás dát...
{36718}{36756}Co takhle na pátého?
{36826}{36870}Mùete to, prosím, vyhláskovat?
{36894}{36950}Budeme potøebovat váš telefon.
{36990}{37035}Vıbornì.|Pøeji krásnı den.
{37035}{37062}Nashledanou.
{37063}{37101}Mùu vám nìjak pomoct?
{37102}{37156}- Jmenuji se Joel Barish.|- Ano?
{37181}{37227}Jsem Joel Barish.
{37234}{37298}- Mám schùzku s doktorem...|- Mierzwiakem.
{37317}{37350}Mùete, prosím, vyplnit toto?
{37351}{37379}Chci si s ním jenom promluvit.
{37380}{37426}Pøesto to, prosím, vyplòte.
{37427}{37466}- Dobøe.|- Dìkuji.
{37532}{37568}Nemám s sebou pero.
{37569}{37606}Pera jsou tam.
{37650}{37678}Dobré ráno, Lacuna.
{37690}{37784}Ano, ta nabídka platila|pouze do konce roku.
{37785}{37819}Pan Barish?
{37892}{37976}- Jak se máte?|- Popravdì øeèeno, nic moc.
{37991}{38042}Proboha, Stane!
{38055}{38107}- Jenom jsem...|- Tady se pracuje.
{38108}{38132}Promiòte.
{38183}{38236}- Prosím, pane doktore.|- Dìkuji.
{38255}{38300}Tohle jste nemìl vidìt.
{38301}{38338}Omlouvám se za to.
{38455}{38509}Je to podvod, e?|Tohle vymyslela Clem.
{38510}{38543}Ujišuji vás, e ne.
{38544}{38575}Ne.
{38736}{38779}Tohle nedává smysl.
{38808}{38888}Naše záznamy jsou|dùvìrné, pane Barishi,
{38889}{38938}take dùkazy|vám ukázat nemohu.
{38945}{39072}Mohu vám pouze sdìlit, e|sleèna Kruczynski nebyla šastná.
{39092}{39137}A chtìla to pøekonat.
{39144}{39200}My tuto monost poskytujeme.
{39201}{39234}Sleèna Kruczynski nebyla šastná?
{39244}{39288}Chtìla to pøekonat.
{39289}{39340}My tuto monost poskytujeme.
{39371}{39408}Co to má znamenat?
{39416}{39470}Já jsem ten|nejmilejší chlap, co zná.
{39470}{39504}Do prdele!
{39528}{39592}Proboha, Robe!|Nech u toho!
{39593}{39681}- To nevadí, Carrie.|- Dìlám ptaèí budku.
{39745}{39829}Co ti mám na to øíct?|Znáš pøece Clementine.
{39829}{39878}Víš, jak je impulsivní.
{39879}{39959}Prostì si tì nechala vymazat|nejspíš jenom z rozmaru.
{40060}{40098}Z rozmaru?
{40266}{40312}Ne, poèkejte!|Tam nesmíte.
{40313}{40362}Omlouvám se, pane doktore,|ale nedal se zastavit.
{40363}{40404}Chci to taky.
{40404}{40458}Øíkala jsem mu,|e teï máme plno.
{40458}{40506}To je v poøádku, Mary.
{40508}{40607}- Spousta lidí ale èeká!|- Pane Barishi, mohl byste jít za mnou?
{40609}{40667}- Mary, mohla by ses postarat|o paní Hungovou? - Ano, pane.
{40668}{40699}Nashledanou, paní Hungová.
{40803}{40867}Take...
{40869}{40969}ne budeme moct zaèít,|je tøeba, abyste zašel domù
{40969}{41107}a pøinesl odtud kadou vìc, která|má nìjakou spojitost s Clementine.
{41121}{41149}Cokoliv.
{41206}{41350}Pouijeme tyto vìci k vytvoøení mapy|Clementine ve vašem mozku.
{41361}{41406}Budeme potøebovat...
{41423}{41489}fotky, obleèení, dárky.
{41495}{41549}Knihy, které vám koupila.
{41550}{41603}Cédéèka, která jste|si koupili spoleènì.
{41613}{41651}Záznamy ve vašem deníku.
{41668}{41723}A odstraníte Clementine|ze svého domova,
{41732}{41797}odstraníte ji|i ze svého ivota.
{41810}{41856}A poté, co vytvoøíme|tuto mapu,
{41856}{41932}vám naši operátoøi dnes v noci|doma provedou zákrok.
{41940}{42008}A a se zítra ráno probudíte,
{42020}{42082}vstanete ze své postele,
{42083}{42136}jakoby se nic nestalo.
{42137}{42188}Bude na vás èekat|úplnì novı ivot.
{42288}{42320}Hleï na cestu, kámo!
{42460}{42504}Ne, omlouvám se.
{42516}{42593}Nemùete mít zákrok|tøikrát za noc.
{42624}{42665}Taková tu máme pravidla.
{42667}{42713}Jak se máte, pane Barishi?
{42733}{42774}Dobrı den.
{42790}{42865}Já vím, e je to naléhavé,|udìlám, co budu moct.
{42865}{42893}Mohli bychom vás zaøadit|na prvního bøezna.
{42894}{42958}Moná byste si mohla|promluvit s doktorem.
{42989}{43030}Dobøe, domluvím vám schùzku.
{43030}{43082}Kdy byste tento tıden|mohla pøijít?
{43082}{43159}- Pane Barishi.|- Je teï velice vytíenı.
{43181}{43262}Zítra ve 12:15 by to bylo|vhodnìjší, vyhovuje vám to?
{43290}{43361}V únoru tu máme|kvùli Valentınu plno.
{43525}{43565}To je Stan Fing,
{43566}{43641}jeden z našich nejzkušenìjších|a nejtalentovanìjších operátorù.
{43682}{43741}Dnes v noci vás|bude mít na starost.
{43742}{43782}Rád vás poznávám,|pane Barishi.
{43810}{43846}Jmenuji se Joel Barish.
{43846}{43952}A jsem tu, abych si nechal vymazat|z pamìti Clementine Kruczynski.
{43975}{44092}Vıbornì.|Teï mi nìco øeknìte o Clementine.
{44103}{44161}Já...
{44161}{44208}il jsem s jednou enou.
{44221}{44251}S Naomi.
{44279}{44311}To bylo pøed pár lety.
{44315}{44406}A mí pøátelé Rob a Carrie mì|vzali na jednu oslavu na plái.
{44406}{44439}Nemám rád oslavy.
{44440}{44487}A Naomi nemohla jít.
{44488}{44551}Já jsem ale šel a...
{44561}{44603}potkal jsem Clementine.
{44639}{44671}Omlouvám se.
{44672}{44767}Zaèneme nejdøíve|od nejnovìjších vzpomínek
{44768}{44813}a budeme postupovat|a k tìm nejstarším.
{44840}{44907}Kadá vzpomínka|má emocionální jádro.
{44908}{45025}Pokud znièíte toto jádro, spustí se|proces degradace celé vzpomínky.
{45031}{45154}Kdy se ráno vzbudíte,|všechny vzpomínky na ní u budou pryè.
{45168}{45230}Bude to, jakoby sen|pokraèoval i po probuzení.
{45230}{45298}Je moné, e by pøi zákroku|došlo k poškození mozku?
{45302}{45423}Technicky vzato je samotnı|proces poškozením mozku.
{45423}{45496}Je to ale podobné tomu,|jako byste se hodnì opil.
{45512}{45553}O nic nepøijdete.
{45584}{45625}Netlaèí vás to?
{45632}{45745}Nyní budeme tvoøit mapu|vašeho mozku, pane Barishi.
{45745}{45789}Vıbornì, mùeme zaèít.
{45789}{45874}Pokud to chceme stihnout do veèera,|tak máme pøed sebou spoustu práce.
{45881}{45946}Mùete prosím reagovat na pøedmìty,|které vám budu ukazovat?
{45946}{45993}Prosím.
{46056}{46121}- K tomu se váe jedna dobrá historka...|- Vlastnì, pane Barishi,
{46122}{46268}emoèní obraz se mi bude tvoøit lépe,|pokud pøedmìty nebudete popisovat nahlas.
{46268}{46316}Pouze se soustøeïte|na vaše myšlenky.
{46317}{46352}- Omlouvám se.|- V poøádku.
{46420}{46493}Zdravá mozková aktivita.
{46493}{46523}Velmi dobøe.
{46533}{46564}Soustøeïte se na další vìc.
{46593}{46630}Další pøedmìt.
{46641}{46675}Dobøe.
{46709}{46756}Bramborové hlavy.
{46758}{46802}Další pøedmìt.
{46851}{46891}Pouze se soustøeïte|na vaše myšlenky.
{46891}{46957}Patricku, pojï mi pomoct.
{46975}{47025}No tak, pomo mi.
{47034}{47103}Mohl bys zkontrolovat|regulátor napìtí?
{47110}{47162}- Tak co tu máme?|- Regulátor napìtí vypadá v poøádku.
{47168}{47226}Opravdu?
{47523}{47587}Zkontroluj ještì pøipojení, prosím.
{47626}{47674}Tady jste.
{47813}{47854}Kde to jsem?
{47867}{47915}Nerozumím tomu,|na co se to právì dívám.
{47916}{47988}Jak mùu stát tady a...
{47988}{48035}Pane Boe! Dejá vu!
{48051}{48087}Dejá vu!
{48099}{48152}- Tohle je tak...|- Mùeme zaèít.
{48152}{48246}Pokud to chceme stihnout do veèera,|tak máme pøed sebou spoustu práce.
{48248}{48290}U jsem ve své hlavì, e?
{48311}{48346}Øekl bych, e ano.
{48364}{48424}To je asi pravda,
{48428}{48472}tak nìjak by to vypadalo.
{48523}{48562}Velmi dobøe.
{48572}{48633}Pokud byste se nezbavil|tìchto pøedmìtù tady,
{48634}{48737}byl byste zmatenı,|a byste je pozdìji doma našel.
{48769}{48809}- Patricku?|- Jo?
{48837}{48877}Patrick!
{48889}{48930}Patrick?
{48937}{49003}- Patrick.|- Proè je na svìtì tolik lháøù?
{49046}{49074}Pomohlo to?
{49161}{49222}Jak se dnes máte,|pane Barishi?
{49249}{49285}Já nevím,|tohle se mi nelíbí.
{49286}{49317}Co takhle zkusit toto.
{49329}{49359}U jsme skoro hotoví.
{49359}{49396}Deník?
{49396}{49429}Je velice cennı.
{49463}{49513}Dnes v noci|jsem nìkoho poznal.
{49514}{49570}Nevím, co mám dìlat.|Jmenuje se Clementine
{49571}{49618}a je úasná.
{49629}{49677}Proboha!
{49678}{49703}- No tak, dávej bacha!|- Co?
{49704}{49739}Zpomal!
{49746}{49782}Buï opatrnı.
{49806}{49830}Dobøe.
{49830}{49883}Nebo toho chlapíka usmaíme.
{49982}{50017}Fajn, to bychom mìli.
{50018}{50062}Tohle je pìkná díra, co?
{50063}{50110}Je to byt, Patricku.
{50166}{50228}Pøipadá mi to tu takové nijaké.
{50229}{50266}Bez nápadu.
{50275}{50334}Je tu cítit nìco zatuchlého.
{50345}{50372}Patricku.
{50373}{50444}Mohli bychom se, prosím,|aspoò chvilièku vìnovat práci?
{50444}{50486}Máme pøed sebou|opravdu pernou noc.
{50487}{50530}- Jasnì.|- Tak pojï sem.
{50638}{50695}Tohle je naposledy,|co jsem tì vidìl.
{51079}{51115}Jsou tøi ráno.
{51116}{51229}Trošku jsem ti|nabourala autíèko.
{51229}{51297}Øídila jsi opilá?|Jsi ubohá.
{51333}{51394}Jsem sice trošièku líznutá,
{51399}{51431}ale neøíkej mi,|e jsem ubohá.
{51432}{51467}To bylo ubohé.
{51468}{51548}Jsi neuvìøitelnì nezodpovìdná,|mohla jsi nìkoho zabít.
{51552}{51627}Tøeba jsi i nìkoho zabila.|Zapneme si zprávy, a se to dozvíme.
{51630}{51666}Nemám jít zkontrolovat kapotu,|jestli na ní nejsou
{51667}{51756}- sraená zvíøátka nebo malé dìti?|- Nikoho jsem sakra nezabila.
{51757}{51792}Plkáš u jak stará babka.
{51792}{51880}Co jsi potom ty?|Násoska?
{51882}{51985}Násoska? Proboha, jsme|snad v padesátıch letech?
{51986}{52024}Násoska?
{52053}{52120}Pøiznej si,|e tì vytáèí myšlenka,
{52121}{52185}e jsem byla|dlouho venku bez tebe.
{52198}{52258}Teï ti v tom tvım|mozeèku vrtá èervíèek,
{52261}{52360}jestli jsem dnes|šoustala s nìkım jinım.
{52399}{52436}Nevrtá, Clem.
{52441}{52498}Pøedpokládám toti,|e jsi s nìkım šoustala.
{52516}{52579}Tak si pøece|získáváš pøátele, ne?
{52834}{52878}Omlouvám se.
{52894}{52946}Clem,|nemyslel jsem to tak, ano?
{53100}{53134}- Klíèe.|- Byl jsem prostì...
{53135}{53186}- U je nebudu potøebovat.|- Prostì jsem...
{53218}{53282}vypìnil, štvala jsi mì.
{53462}{53490}Clem?
{53550}{53575}Mám to.
{53618}{53675}- Zastaví se tu Mary.|- Jo?
{53676}{53737}Jo. Øíkám ti to pøedem,|a s tím poèítáš.
{53738}{53767}Mám rád Mary.
{53767}{53827}Jenom si myslím,|e ona nemá ráda mì.
{53827}{53863}Má tì ráda.
{53887}{53956}Moná bych si mohl|taky pøivést svoji holku.
{53956}{54015}- Já toti teïka s nìkım chodím.|- S ivou holkou?
{54020}{54075}Co je na tom tak...?|Jasnì.
{54203}{54243}U jsem ti to øíkal,|e mám holku?
{54244}{54292}Musím se tu|soustøedit, Patricku.
{54315}{54451}Problém je v tom,|e je to trošku divnı.
{54452}{54491}To s mojí holkou.
{54494}{54531}To jsem si teda jistı, e je.
{55206}{55247}Clem, vezmu tì domù.
{55248}{55308}Dej mi pokoj, úchyle!
{55336}{55367}Podívej se kolem.
{55368}{55412}Celı svìt se hroutí.
{55421}{55484}Mau si tì z pamìti|a jsem šastnı!
{55485}{55537}Ty jsi mi to udìlala první.
{55538}{55588}Jak jsi mi to mohla udìlat.
{55635}{55688}Clem! Slyšíš mì?
{55697}{55757}Do rána budeš pryè.
{55761}{55845}Perfektní konec|tohodle posranıho pøíbìhu.
{55977}{56041}Je na tom nìco špatného,|kdy se mi líbí holka?
{56042}{56120}- Máš s tím problém?|- Ne, myslím, e je to zajímavé.
{56129}{56173}Kdo si myslíš,|e vypadá líp?
{56174}{56205}Já nebo tenhle chlápek?
{56206}{56249}Patricku, radši se|soustøeï na práci.
{56252}{56300}Vzpomínáš si na tu|dívku z minulého tıdne?
{56316}{56378}Tu s bramborami.
{56438}{56471}Tamtu dívku?
{56472}{56539}Jo, bıvala to holka|tady toho chlápka.
{56602}{56666}Co je s ní?
{56667}{56763}Tehdy v noci jsem se|do ní trošku zamiloval.
{56771}{56855}- Coe? Ty ses do ní zamiloval?|- Co je?
{56855}{56911}Nebyla pøi smyslech, kámo.
{56923}{56983}Byla krásná.
{57008}{57055}Vzal jsem si její kalhotky.
{57137}{57197}- Jeiši!|- Co? To není tak...
{57198}{57236}Ty kalhotky byly èisté.
{57237}{57294}Neøikej mi tyhle úchylárny,|u to nechci slyšet.
{57294}{57357}- Byly èisté.|- Ne, nech toho.
{57358}{57407}- Dobøe.|- Máme spoustu práce.
{57407}{57437}Fajn.
{57862}{57898}Je tu ještì nìco.
{57968}{58089}Potom, co jsme to dodìlali,|jsem za ní zašel do práce.
{58145}{58172}Coe jsi?
{58178}{58253}- Proboha!|- Proboha, Patricku!
{58295}{58459}- Uvìdomuješ si vùbec, jak je to neetické?|- Ale ne, to pøece není tak špatné.
{58468}{58527}Co? Proè se tak tváøíš?|Nìco se ti nelíbí?
{58528}{58612}Patricku!|Ukradl jsi té holce kalhotky.
{58897}{58934}Nìkdo tu je.
{58970}{59029}Ukradl ti spodní prádlo.
{59034}{59069}Já tu nikoho nevidím.
{59529}{59553}Joele?
{59561}{59601}Kde mám boty?
{59975}{60074}Já z tebe snad|vyletím z kùe.
{60122}{60178}Mìla jsem tì|nechat na blešáku.
{60562}{60618}Chtìla bych mít miminko.
{60643}{60685}Promluvíme si o tom pozdìji.
{60686}{60752}Ne, já chci mít miminko.
{60788}{60829}Myslím, e na to|ještì nejsme pøipravení.
{60853}{60892}Ty ještì nejsi pøipravenı.
{60932}{60995}Clem, ty si vánì myslíš, e|bychom se byli schopní postarat o dítì?
{61004}{61048}Ale ne, coe?
{61092}{61133}Tady se o tom bavit nechci.
{61134}{61204}Já jsem tì slyšela a nerozumím|tomu, co jsi tím chtìl, kurva, øíct.
{61205}{61244}Nechci se o tom bavit.
{61257}{61308}- My se o tom teda bavit budeme.|- Já se nechci o tom...
{61309}{61384}Nemùeš øíct nìco takového,|kdy se o tom nechceš bavit.
{61384}{61442}- Omlouvám se.|- Byla bych zatracenì dobrá matka.
{61442}{61564}Mám ráda dìti, jsem kreativní a chytrá|a prostì byla bych vıborná matka.
{61572}{61652}To ty, Joele!
{61653}{61722}Máš bıt rád, e se|o tebe vùbec zajímám.
{61723}{61793}Moná bych to mìla|skonèit právì teï.
{61798}{61890}Nechat tì na bleším trhu.
{62201}{62245}- Ahoj, Patricku.|- Ahoj, Mary, jak se máš?
{62246}{62287}Venku strašnì mrzne.
{62297}{62353}- Nezabloudila jsi?|- Ne.
{62537}{62569}Chudáèek.
{62645}{62766}- Nemáte nìco normálního k pití?|- Ještì jsme se nedívali.
{62767}{62785}Patricku?
{62785}{62822}Nech to na mnì.
{62822}{62866}Já se podívám.
{62906}{62946}Nesnáší mì.
{62950}{62998}Na enskı nìjak|nemám štìstí.
{62999}{63062}Moná bys jim mìl|pøestat krást kalhotky.
{63098}{63193}- Stane, mohl bych?|- Ne!
{63310}{63359}Ty jsi nechtìl, e, Patricku?
{63360}{63409}Ne, nechtìl, díky.
{63441}{63542}"Poehnáni jsou zapomnìtliví,|nebo si berou to lepší i ze svıch omylù."
{63807}{63845}To napsal Nietzsche.
{63849}{63923}V Mimo dobro a zlo.|Našla jsem to v Bartlettovi.
{63935}{63976}Co je to Bartlett?
{63992}{64031}Je to kníka, Patricku.
{64032}{64087}Soubor citátù.
{64087}{64143}Myslím, e Howard taky|jednou bude v Bartlettovi.
{64144}{64199}To rozhodnì, Howard je|pøímo zralı na Bartletta.
{64287}{64375}- Nemùete ho probudit?|- Ne, toho nemùeš vzbudit.
{64575}{64629}Vùbec se mnou|nekomunikuješ, Joele.
{64669}{64718}Já jsem jak otevøená kniha.
{64749}{64797}Všechno ti hned vyklopím.
{64797}{64877}Kadou trapnou blbùstku,|co se mi stane.
{64937}{64986}Ty mi nevìøíš?
{64997}{65079}To, e nepøetritì mluvíš|ještì neznamená, e komunikuješ.
{65137}{65177}To nedìlám.
{65241}{65293}Chci tì poznat.
{65358}{65408}Nemluvím nepøetritì!
{65417}{65449}Proboha!
{65489}{65556}Musíš sdílet|svı proitky, Joele.
{65583}{65634}Tomu se øíká intimita.
{65656}{65711}To mì fakt vytoèilo,|co jsi øekl.
{65712}{65747}Promiò.
{65748}{65833}Mùj ivot prostì|není tak zajímavı.
{65858}{65931}A co ten tvùj deník,|kterı si vedeš.
{65932}{66058}Co si tam potom píšeš, kdy nemáš|ádnı myšlenky, touhy nebo lásky.
{66226}{66322}19. listopadu 2003.
{66340}{66402}Další veèeøe v Kings.
{66450}{66590}Nejsme u jako ty znudìné páry,|které v restauracích tak litujeme?
{66603}{66654}Nejsme jako veèeøící mrtvoly?
{66666}{66755}Nesnesu, e by si to|o nás nìkdo mohl myslet.
{66979}{67011}Jak ti chutná kuøe?
{67036}{67069}Chutná.
{67099}{67165}- Chceš?|- Ne, díky.
{67235}{67291}Teï se opije a zase se|bude chovat jako kráva.
{67303}{67400}Hele, mohl by sis oddìlávat|svoje chlupy z mıdla potom,
{67402}{67429}co se osprchuješ?
{67430}{67479}- Jasnì.|- Je to vánì...
{67481}{67523}- Nechutnı.|- nechutnı.
{67583}{67615}Prostì to je...
{67619}{67675}- Odpornı.|- odpornı.
{67824}{67868}Patricku, mùeme projít tohle?
{67884}{67915}Patricku.
{67988}{68020}Patricku, zlato.
{68058}{68106}Je mi tak hroznì.
{68124}{68152}Jak to? Co se stalo?
{68153}{68229}Já nevím,|jsem tak zmatená.
{68236}{68268}Hledáte nìco, pane?
{68269}{68318}Zmatená?|Proè bys mìla bıt zmatená?
{68319}{68348}Všechno je v poøádku.
{68560}{68620}- Máš mì rád?|- Jasnì, e mám.
{68628}{68675}Kdo si to tu hojí sebevìdomí?
{68701}{68783}- Myslíš si, e jsem odporná?|- Ne, jsi nádherná.
{68788}{68847}- Moná bych mìl za tebou zajít.|- Ne, nechoï.
{68851}{68955}Já nevím, jsem hroznì|znièená, Patricku.
{68956}{69011}Proto bych se mìl stavit,|abych ti zlepšil náladu.
{69015}{69043}Dobøe.
{69044}{69083}Stane, mohl bych si|na chvilku odskoèit?
{69090}{69137}- Mojí holce je špatnì.|- Patricku,
{69145}{69224}- pøímo uprostøed mazání?|- Jen ho nech, Stane.
{69230}{69270}A jde. Já ti pomùu.
{69301}{69386}Vidíš? Nesnáší mì.|Chce, abych šel pryè.
{69386}{69417}Bì.
{69457}{69498}Hned jsem u tebe, Mandarinko.
{69502}{69530}Líbí?
{69622}{69675}Dokonale se mi hodí.
{69676}{69710}- Líbí se mi.|- Opravdu?
{69711}{69761}Vypadáš jako mandarinka.
{69773}{69841}Mandarinka klementinka.
{69843}{69885}Šavnatá a bez pecek.
{69889}{69922}To se mi líbí.
{69960}{70030}Mì se zase líbí Mandarinka.
{70031}{70095}- U jsem ti ukazovala,|jak dìlám kaèenku?  - Ne.
{70095}{70133}Jsem kaèenka.
{70137}{70173}Odkud ví, e|jsem ti tak øíkal?
{70173}{70210}Kdo to ví?
{70211}{70250}- Mùj Boe!|- Tohle je super.
{70251}{70272}Clem?
{70272}{70335}Tak si øíkají, The Clash.
{70336}{70425}Jediná kapela, co za nìco stojí.|Mají dùvod, proè se tak jmenují.
{70426}{70475}- Je to úasné...|- Jsou jako soudci téhle spoleènosti.
{70476}{70519}Jo, je to fakt fantastické.
{70519}{70573}Je úasné,|co Howard dává svìtu.
{70614}{70647}No jo.
{70654}{70721}Dává lidem novou šanci.
{70762}{70945}Kdy se díváš na novorozenì,|je tak neposkvrnìné, je jako nepopsanı list.
{70948}{71100}A kdy jsi dospìlı, tak se poøád|plácáš ve svıch depresích a fobiích.
{71105}{71160}A díky Howardovi to|mùe všechno zmizet.
{71484}{71532}- Lásko, co se dìje?|- Já nevím.
{71533}{71600}Já nevím. Mám pocit,|e nevím, kdo jsem. Bojím se.
{71610}{71648}Jako kdybych mizela.
{71649}{71713}Mám vrásky,|pøipadám si stará.
{71713}{71781}- Nic mi u nedává smysl.|- Vùbec nejsi stará.
{71781}{71825}Nic nedává smysl.
{71825}{71881}- Nic nedává smysl.|- Mandarinko.
{71881}{71917}Nic nedává smysl.
{71941}{71977}Nic nedává smysl.
{71978}{72025}To bude dobrı.
{72026}{72067}Pojïme si nìkam zatanèit.
{72068}{72140}Pojedeš se mnou|do Montauku?
{72141}{72182}- Do Montauku?|- Ano... ne!
{72189}{72261}- Pojedeme spolu do Bostonu.|- Jasnì, mùeme jet pøíští tıden.
{72262}{72309}Ne, ne, teï.
{72310}{72409}Pojedeme tam teï.|Chci teï vidìt øeku Charles.
{72501}{72547}Ahoj, dovolali jste se k Joelovi.
{72575}{72629}Svoji zprávu mùete zanechat|po zaznìní zvukového signálu.
{72647}{72698}Já se za chvilku vrátím.
{72722}{72770}Zvedni to, Stane, zvedni to.
{72903}{72935}Haló?
{72943}{72971}Co se dìje?
{72973}{73027}Mám tady takovı problém.
{73039}{73111}Myslíš, e by šlo, kdybych se|dneska u nevrátil? Je mi to fakt líto.
{73112}{73171}Nemìj strach,|všechno mám pod kontrolou.
{73172}{73224}Stejnì je teï na autopilotovi.
{73225}{73263}Díky, Stane.|Máš to u mì.
{73264}{73307}Musím u jít, kámo.
{73632}{73687}Podívej, já a ty u øeky Charles.
{73692}{73735}Mohl bych zemøít|právì teï, Clem.
{73736}{73774}Jsem tak šastnı.
{73775}{73844}Ještì nikdy jsem se tak necítil.|Jsem pøesnì tam, kde chci bıt.
{73884}{73916}Hroznì se tìším!
{73924}{73964}Já taky.
{74072}{74113}Nìco pro tebe mám.
{74145}{74169}Dárek.
{74190}{74244}Šastného Valentına.
{74357}{74390}Co je to?
{74391}{74436}Nevím. Otevøi to.
{74624}{74669}- Je to nádhernı.|- Líbí se ti?
{74670}{74718}Je pøesnì podle mıho vkusu.
{74725}{74805}Ještì nikdy jsem od kluka|nedostala šperk, co by se mi líbil.
{74829}{74861}Díky.
{75089}{75169}- Joelie?|- Copak, Mandarinko?
{75206}{75249}Jsem škaredá?
{75305}{75351}Kdy jsem byla malá,|tak jsem si myslela, e jsem.
{75395}{75450}Nemùu uvìøit, e|kvùli tomu ještì poøád breèím.
{75466}{75582}Nìkdy mi pøipadá, e si lidi|neuvìdomují, jak jsou dìti osamìlı.
{75603}{75703}Máš pocit, e|na tobì vùbec nezáleí.
{75713}{75852}Je mi osm a mám všechny|tyhle hraèky, panenky.
{75855}{75966}Moje oblíbená je jedna opravdu|škaredá panenka, kterı øíkám Clementine.
{75972}{76020}A já na ní poøád køièím.
{76022}{76109}Nesmíš bıt škaredá.|Buï krásná!
{76126}{76158}Je to zvláštní.
{76159}{76299}Je to, jako kdyby, kdy dokáu|promìnit ji, promìním se kouzlem i já.
{76426}{76458}Jsi krásná.
{76459}{76500}Joelie.
{76518}{76612}- Nikdy mì nesmíš opustit.|- Jsi krásná, jsi krásná...
{76632}{76679}Doktore Mierzwiaku.
{76689}{76745}Prosím, nechte mi|aspoò tuhle vzpomínku.
{76746}{76791}Jenom tuhle jednu.
{76791}{76837}Nechci tì dret za ruku, pojï.
{76947}{76973}Zastav!
{77035}{77097}Mohl bych zemøít|právì teï, Clem.
{77146}{77193}Jsem tak...
{77212}{77258}šastnı.
{77323}{77396}Ještì nikdy|jsem se tak necítil.
{77456}{77621}Jsem pøesnì tam,|kde chci bıt.
{77664}{77696}Clem?
{77841}{77871}Proboha!
{77889}{77935}Jak to mùu zastavit?
{78057}{78105}Chci to skonèit!
{78150}{78252}Slyší mì nìkdo?|U to nechci, chci skonèit.
{78417}{78502}Je tam nìkdo?
{78670}{78702}Kdokoli.
{78758}{78786}Joelie?
{78786}{78834}- Clem?|- Joele?
{78834}{78866}Clem.
{78905}{78978}- Co se dìje?|- Musíme jít pryè.
{78979}{79022}Napadlo mì,|jak to zastavit.
{79023}{79050}Zastavit co?
{79079}{79126}- Joelie?|- Pospìš.
{79316}{79360}Soustøeï se, Clem.
{79434}{79466}Byl tam magnetofon.
{79467}{79526}Ne, obrázek ne!
{79578}{79618}Zpátky! Tudy!
{79631}{79691}Podívej na mì...
{79698}{79781}Naše záznamy jsou|dùvìrné, pane Barishi,
{79782}{79813}take dùkazy|vám ukázat nemohu.
{79821}{79967}Mohu vám pouze sdìlit, e|sleèna Kruczynski nebyla šastná.
{79968}{80003}A chtìla to pøekonat.
{80015}{80122}- Nyní mi povìzte o Clementine.|- "Øeknìte mi všechno, na co si vzpomenete."
{80123}{80145}To øíkal.
{80145}{80187}Co jsme to tehdy hledali?
{80188}{80231}- Ne, poèkej.|- Podívej!
{80232}{80285}- Do háje!|- Jedeme k mojí babièce.
{80297}{80349}- Joele, co...|- Vlakem nejedeme.
{80350}{80426}- Joele, prosím, já u nechci utíkat.|- Honem!
{80435}{80470}Mierzwiaku!
{80491}{80542}- Musíme poøád utíkat?|- Mierzwiaku!
{80792}{80824}Prosím...
{80836}{80981}Take, zaèneme tím, e mi|povíte vše, co si pamatujete.
{80981}{81026}Mierzwiaku, vzbuïte mì!
{81053}{81165}Omlouvám se, pane Barishi,|ale musíte pochopit, co se tu dìje.
{81179}{81241}Ne, maete ji ze mnì.
{81254}{81297}Maete mì z ní.
{81385}{81416}Já nevím.
{81421}{81491}Máte tu vìc.|Jsem ve své posteli.
{81492}{81523}Vím to.
{81525}{81563}Mùj mozek.
{81563}{81641}Já jsem také souèást|vaší pøedstavivosti, Joele.
{81645}{81720}Jak mùu pomoci ven?
{81720}{81782}Jsem také ve vaší hlavì.|Já jsem vy!
{81854}{81882}Omlouvám se.
{81890}{81934}Kdo je to?
{81935}{81993}Pracuje pro nás.
{81994}{82023}To je...
{82023}{82096}Patrick.
{82097}{82148}Chlapeèek.
{82164}{82199}Ukradl mi moji identitu.
{82227}{82266}Ukradl moje vìci.
{82278}{82376}Svádí mi moji dívku|mımi slovy a vìcmi.
{82377}{82413}Ukradl jí spodní prádlo.
{82440}{82503}Jeiši, on jí ukradl|spodní prádlo.
{82518}{82572}Mohl bych zemøít|právì teï, Clem.
{82578}{82637}Jsem tak šastnı.
{82647}{82702}Ještì nikdy|jsem se tak necítil.
{82702}{82763}Jsem pøesnì tam,|kde chci bıt.
{82799}{82831}Chci se vrátit domù.
{82887}{82923}Coe?
{82982}{83010}Clem!
{83059}{83087}Poèkej, Clem!
{83145}{83169}Clem?
{83180}{83215}Maou tì.
{83295}{83367}Clem? Soustøeï se.|Najal jsem si je.
{83368}{83405}Promiò, jsem hlupák.
{83405}{83447}Zlato, uklidni se.
{83448}{83514}- Uivej si pøírodu.|- Musíme to zastavit.
{83515}{83564}Døív, ne se probudím|a u tì nebudu znát.
{83615}{83694}No, tak dobøe.|Tak to zruš.
{83695}{83744}O èem to sakra mluvíš?
{83744}{83792}Nemùu to zrušit, já spím.
{83809}{83916}- Tak se vzbuï!|- Dobøe, vzbudím se, dobøe, jdu na to.
{83917}{83960}- Jsi spokojená, e to zkouším?|- Jo.
{83961}{84000}Musím se opravdu soustøedit.
{84000}{84052}Jdu na to,|je to skvìlı nápad.
{84074}{84106}Dobøe.
{84120}{84176}Jsem jak figurka z animáku.
{84265}{84306}Mùj ty Boe, Mary?|Co to je?
{84307}{84353}Je to znamínko!
{84424}{84472}Fungovalo to. Na chvilku.
{84504}{84532}Vidíš?
{84539}{84580}Nemohl jsem se hıbat.
{84580}{84608}No...
{84609}{84670}Doufám, e to není zase|jeden z tìch tvıch pokusù,
{84671}{84733}jak mi dokázat,|e nikdy nemám pravdu.
{84733}{84793}O tom se teï|nechci bavit, dobøe?
{84817}{84844}Fajn.
{84896}{84937}Tak co teï?
{84947}{84996}- Poslouchám.|- Já nevím.
{84997}{85095}Ty sis mì vymazala jako první,|proto to teï dìlám.
{85096}{85133}- Omlouvám se.|- Ty!
{85134}{85183}Víš, jak jsem impulsivní.
{85286}{85337}Právì to mám na tobì rád.
{85426}{85459}Joele?
{85483}{85536}Mám další nápad,|jak tohle vyøešit.
{85547}{85586}Tohle je vzpomínka na mì.
{85587}{85657}Jak jsi mìl chu mít|se mnou sex na gauèi,
{85658}{85701}potom, co jsi|vidìl mùj rozkrok.
{85723}{85795}Joele, jdou sem|a chtìjí mì vymazat.
{85808}{85855}Co kdybys mì|vzal nìkam jinam?
{85855}{85900}Nìkam, kam nepatøím.
{85908}{85955}Kde se schováme|do zítøejšího rána.
{86083}{86156}Zatracenì, nevzpomínám|si na nic, kde bys nebyla.
{86193}{86267}- To je sice moc milı, ale sna se víc.|- Dobøe.
{86876}{86913}Funguje to!
{86940}{86980}Jsem geniální.
{87508}{87541}Joele?
{87572}{87608}Joele?
{87632}{87680}Kam jsi zmizel?
{87680}{87733}Mám jít s tebou taky.
{87733}{87770}Poslyš,|musím na chvilku odejít.
{87771}{87825}Mohla bys dohlédnout|na polévku a na Joela?
{87826}{87893}- Je zvyklı bıt se mnou.|- Samozøejmì.
{87898}{87949}- Clem?|- Vyšlo to.
{87961}{88001}Proboha, podívej se!
{88002}{88045}Ono to vyšlo!
{88067}{88117}Podívej se na ty šaty.
{88133}{88205}Páni, jsou skvìlı, ké bych|si je tak mohla vzít s sebou.
{88255}{88281}Kdo jsem?
{88282}{88333}- Paní Hamlinová.|- Jasnì, paní Hamlinová.
{88334}{88372}Musí mi bıt tak ètyøi roky.
{88372}{88404}A jejda.
{88423}{88551}- U jsem zpátky i s mísou na salát.|Je všechno v poøádku?  - Jasnì.
{88551}{88605}Budu muset celı den uklízet.
{88606}{88677}Vadilo by ti, kdybys mi|pomohla umıt tyhle fazole?
{88678}{88710}Ne, vùbec ne.
{88722}{88758}Tahle kuchyò je úasná.
{88759}{88811}Díky.
{88812}{88869}Vùbec se na mì nepodívá.|Má práci.
{88878}{88926}- Tohle je tak...|- Nedívá se na mì.
{88927}{88967}Nikdo se na mì nedívá.
{88967}{89006}Já chci maminku.
{89007}{89040}Ó, zlatíèko.
{89041}{89122}- Hej, Joele.|- Je všechno v poøádku?
{89123}{89158}Ano, nic se nedìje.
{89159}{89226}- Nemìla bys nìco k pití?|- Piješ koktejly u tak brzo?
{89227}{89297}- Ještì není pìt hodin.|- Koktejl by bodnul.
{89297}{89335}- Tak chvilku vydr.|- Dobøe.
{89335}{89400}To je jako sen.|Joele. Ne, zlato.
{89415}{89442}Joelie?
{89443}{89531}Tvoje matka chce, abych na tebe|dávala pozor, tak se vra pod stùl.
{89531}{89638}- Chci zmrzlinu.|- Ne, nemùeš mít zmrzlinu pøed obìdem.
{89639}{89667}No tak, Joele.
{89705}{89760}- Joele, uvìdom si, kolik ti je!|- Neopouštìj mì, Clem.
{89760}{89823}U jsem tady. Vyšlo to.
{89824}{89864}Bojím se.
{89864}{89929}- Kde je maminka.|- Neplaè, brouèku.
{89929}{90001}Bude to v poøádku.|Joele!
{90033}{90057}Joele, nech toho!
{90058}{90128}Vypadá to, e to vyšlo.|Schovali jsme se.
{90144}{90172}Podívej se.
{90179}{90228}Chvilku poèkej.
{90308}{90392}Rozkrok je poøád tady.|Pøesnì, jak si ho pamatuješ.
{90393}{90428}Fuj.
{90526}{90568}Zastavilo se to!
{90569}{90605}Coe?
{90609}{90656}Mazaní se zastavilo.
{90657}{90717}Do prdele!
{90717}{90761}To je hroznı.
{90817}{90865}Sjel z mapy.
{90865}{90906}- Kam?|- Nemám ponìtí.
{90907}{90945}Jak to myslíš?|Nevím, kam zmizel.
{90946}{91021}Tohle je zlı, moc zlı.
{91022}{91057}Kde mám brıle?
{91058}{91086}Dobøe.
{91087}{91191}Do háje!|Co mám dìlat?
{91191}{91249}- Co budeme dìlat?|- Já nevím.
{91250}{91321}- Co budeme dìlat?|- Nevím! U jsem ti to øíkal.
{91322}{91386}- Omlouvám se, co udìláme?|- Já nevím.
{91387}{91482}- Nech toho, vytáèí mì to.|- Nìco ale musíme udìlat.
{91488}{91530}- Musíme ho vzbudit.|- Uklidni se.
{91531}{91577}Ticho, rozèiluješ mì.
{91578}{91653}Co kdy se nám usmaí?
{91673}{91722}- To zní dobøe.|- Sakra!
{91722}{91777}- Dostala jsem hlad.|- Zatracenì!
{91783}{91837}Co?
{91850}{91922}- Mìli bychom zavolat Howardovi.|- Ne, to nemùeme.
{91923}{91975}Tohle je moje práce,|já to zvládnu.
{91975}{92019}Nemùeme do toho|zatahovat Howarda.
{92058}{92138}- Nemáme èas na blbosti.|- Mám to pod kontrolou.
{92139}{92186}Mìli bychom se ho zeptat.
{92187}{92241}Dobøe, zavolám Howardovi.
{92414}{92454}- Haló?|- Ahoj, Howarde.
{92455}{92534}Tady je Stan.|Dìlám tady na tom chlápkovi
{92535}{92599}a vypadá to,|e jsem ho ztratil.
{92600}{92658}A teï ho nemùu najít.
{92658}{92747}Dobøe, øekni mi,|co se stalo pøedtím, ne zmizel.
{92747}{92827}Nejsem si úplnì jistı,|na chvilku jsem si odskoèil.
{92827}{92930}Tak jsem ho dal na autopilota,|protoe jsem musel na záchod.
{92930}{92967}A kde je Patrick?
{92968}{93028}Patrick šel domù,|protoe mu nebylo dobøe.
{93029}{93076}Jeiši.
{93095}{93129}Dobøe, jaká je to adresa?
{93129}{93181}- Omlouvám se.|- To je v poøádku.
{93182}{93243}- South Village 159.|- Ano.
{93244}{93315}Byt 1E, Rockville Center.
{93316}{93371}Mary, jede sem.
{93382}{93421}Já zùstávám tady.
{93423}{93475}- Nech toho, Mary.|- Zùstanu tu.
{93484}{93524}Mìla bys jít pryè.
{93525}{93575}- Ne.|- Mary.
{93608}{93640}Sakra!
{93641}{93717}- Jsem tak sjetá.|- Prosím tì, Mary.
{93741}{93797}- Musíš zmizet.|- Jsem hroznì sjetá.
{93797}{93853}Nechci, aby mì vidìl sjetou.
{93861}{93966}Mary, nemáš ponìtí, v jakém budeme|prùšvihu, kdy tì tu Howard najde.
{93967}{94014}Joele, nech toho.
{94014}{94045}Hej, Joele!
{94181}{94227}- Joele.|- Chci, aby mì vzala do náruèe.
{94227}{94277}Je to zvláštní, silná touha.
{94278}{94328}Joele, podívej se na mì.
{94333}{94373}Ráno si mì budeš pamatovat.
{94374}{94465}A pùjdeš za mnou, øekneš mi|o nás a zaèneme od znova.
{94468}{94557}Myslela jsem,|e si spolu dáme koktejl.
{94569}{94599}Patrick, ten chlap.
{94599}{94645}Kopíruje mì.
{94646}{94677}Jakı Patrick?
{94678}{94734}- Byl tady.|- Coe?
{94746}{94810}V mém bytì.|Je to jeden z nich.
{94811}{94862}Zamiloval se do tebe,|kdy ti mazali pamìt.
{94862}{94936}A teï se tváøi, jako by tì|vùbec neznal a chodí s tebou.
{94950}{95009}Opravdu?
{95030}{95070}Je hezkı?
{95110}{95160}Clem, není na tobì|nic špatného.
{95160}{95237}Jsi ten nejúasnìjší|èlovìk, co znám.
{95265}{95299}Jsi laskavá.
{95320}{95417}Jsi krásná, chytrá, zábavná.
{95417}{95490}A... milá.
{95502}{95539}Coe?
{95574}{95606}Dobøe.
{95711}{95779}Honem. Pohni se.
{95803}{95858}Sakra, jsem úplnì v háji.
{95895}{95955}Ty oèní kapky,|co jsi mi dal, jsou nanic.
{96079}{96129}Hlavnì klidnì.
{96223}{96307}- Ahoj, Mary, co ty tady dìláš?|- Ahoj, Howarde, pøijela nám pomoct.
{96308}{96399}Pøijela jsem, abych lépe|pochopila celou proceduru.
{96400}{96529}Myslím, e je dùleité pro moji práci,|abych rozumìla tomu, co dìláme.
{96530}{96717}Teda, ne, co já dìlám, ale co dìlají lidi,|se kterımi pracuji, moji kolegové.
{96728}{96832}Dobøe, rád bych se|teï podíval, co se stalo.
{96953}{97013}- To je zvláštní.|- To jsem u zkoušel.
{97013}{97088}- Zkoušel jsi pouít bránu C?|- No jasnì, si piš.
{97096}{97152}Chtìl jsem øíct, ano.
{97176}{97209}Vıbornì.
{97264}{97296}Dobøe.
{97344}{97401}- Pøinesl sis svùj laptop?|- Ano.
{97463}{97558}Prošel jsem osobnostní program,|ale nic jsem nenašel.
{97559}{97641}Tak jsem zkontroloval všechny vzpomínky,|jestli nemají podprahové bloky.
{97657}{97715}Howarde,|pøinesla jsem vám idli.
{97718}{97780}Dìkuji.
{97802}{97845}Dobøe.
{97846}{97939}Musím projít celou pamì,|jestli se nìkde neschovává.
{98107}{98162}Moc rád se koupu ve vılevce.
{98163}{98212}Mám rád ten pocit bezpeèí.
{98229}{98286}Nikdy jsem tì|nevidìla šastnìjšího.
{98306}{98345}U jsem ho našel.
{98354}{98438}Nerozumím tomu,|proè tak sjel z mapy.
{98471}{98518}Co tam sakra dìlá?
{98743}{98780}Otevøel oèi.
{98839}{98899}- Udìlal to u pøedtím?|- Ne.
{98923}{98984}Tohle není dobré.
{99058}{99107}Musím mu dát injekci.
{99700}{99768}Copak to nechápeš?|Miluji tì, Antoine.
{99784}{99828}Dobøe, je zpátky.
{99838}{99867}Páni.
{99876}{99922}To bylo nádherné, Howarde.
{99923}{100012}Bylo to jako pozorovat pøi práci|chirurga nebo klavírního virtuosa.
{100052}{100084}Dìkuji, Mary.
{100116}{100188}Howarde, asi u mùeš jít zase spát.|Všechno vypadá v poøádku.
{100189}{100225}Copak to nechápeš?
{100226}{100284}Miluji tì, Antoine.
{100324}{100355}To mám teda štìstí.
{100355}{100385}Doka mi to.
{100500}{100568}Neøíkej mi Antoine.|Jmenuji se Wally.
{100569}{100654}Já vím, jak bych ale mohla milovat|nìkoho, kdo se jmenuje Wally?
{100683}{100717}Co to bylo?
{100725}{100781}Proboha,|ze zadku ti vylézají lidé.
{100782}{100814}Opravdu?
{100879}{100930}- Mám to.|- Mandarinko!
{100947}{101008}Musíme zmizet.
{101145}{101191}Utíkat mùeš,|ale nikdy se neschováš.
{101192}{101233}Clem, pospìš!
{101258}{101292}Támhle jsem.
{101350}{101387}Doktore!
{101401}{101445}Prosím!
{101456}{101588}Take, zaèneme tím,|e mi povíte vše, co si pamatujete.
{101590}{101671}To je zvláštní, je ve vzpomínce,|kterou jsme u jednou mazali.
{101684}{101791}Aspoò u víme,|kde je, zpátky na cestì.
{101820}{101890}Vypadá to, e si vyvinul nìjakı|zpùsob obrany proti proceduøe.
{101891}{101929}Já u nechci utíkat.
{101955}{101983}Do háje!
{102015}{102039}Pojï.
{102040}{102104}Schovej mì hloubìji,|úplnì na spodek.
{102126}{102167}Schovej mì|do svıho poníení.
{102197}{102231}- Do poníení?|- Jdeme!
{102551}{102592}Poèkej, Howarde.
{102615}{102663}Zase zmizel.
{102665}{102704}Zatracenì.
{102735}{102771}Je mi to líto, Howarde.
{102772}{102803}Poníení.
{102827}{102860}Poníení.
{102880}{102947}- Poní...|- Joele.
{102976}{103011}Mì se to taky nelíbí.
{103011}{103060}Jenom jsem se snail vybrat|nìjaké pøíšerné, tajné místo.
{103061}{103116}Zlato, mám pro|tebe pøekvapení.
{103152}{103208}Víš co, zlato?|Zeptám se tì radìji ráno.
{103225}{103268}Dobrou noc, brouèku.
{103348}{103408}- Chudáèku Joelie.|- Sklapni!
{103439}{103472}Podívej!
{103473}{103508}Joele!
{103511}{103552}- Joele, podívej se.|- Co je?
{103557}{103600}Podívej se, kde to jsme.
{103621}{103645}Ale ne.
{103665}{103689}Clem?
{103694}{103728}Tohle není dobré.
{103733}{103828}Tak mì schovej nìkde|doopravdy hluboko.
{103831}{103901}Do toho, Joele.
{103901}{103942}Nemùu, musím u jít domù.
{103942}{103990}- Dìlej!|- Udìlám to pozdìji!
{103990}{104050}Udìlej to!
{104066}{104109}Nebuï slaboch.
{104459}{104535}- On má u holku.|- Poèkej, co to dìlám?
{104536}{104596}Víš co, Freddy?|U se tì nebojím.
{104649}{104681}Joele?
{104681}{104738}Joele, vstávej.|Nestojí za to.
{104739}{104786}Nestojí ti za to, Joele.
{104824}{104898}- Neposlouchá!|- Blbèe!
{105054}{105094}Já se tak stydím.
{105095}{105134}To je v poøádku.
{105138}{105190}- Jsi malı kluk.|- Jo.
{105191}{105232}- Pojï.|- Tady iju.
{105233}{105266}il jsem.
{105267}{105319}Škoda, e jsem tì neznal,|kdy jsem byl malı.
{105320}{105345}Líbí se ti mùj rùovı klobouk?
{105345}{105426}Jestli se ti uleví, tak mì teï|mùeš doopravdy zabít.
{105427}{105478}- Udìlej to.|- Opravdu? Vánì chceš zemøít?
{105479}{105534}- Tak dobøe.|- Raz, dva, tøi.
{105534}{105575}Jsi mrtvá.
{105589}{105630}Moje máma.
{105631}{105697}- To je v poøádku, jenom si hrajeme.|- Ahoj, Joelova maminko.
{105698}{105740}Jenom se mì snaí zabít.
{105758}{105820}U jsi mrtvá?|Jsi mrtvá!
{105852}{105917}Myslím, e to dokáu zvládnout,|ale poøád tomu nerozumím.
{105917}{105973}Naštìstí ho|dokáu rychle najít.
{106837}{106861}Joelie?
{106872}{106909}Jsi v poøádku, Joele?
{106930}{106981}Joele?
{107009}{107059}Proboha, to bylo hroznı.
{107077}{107127}To byly aspoò tøi vteøiny.
{107127}{107197}Ještì jednou a dostanu tì.
{107509}{107557}- Podívej se.|- To je super.
{107771}{107814}Dùm!
{107926}{107966}Poèkej, musíme jít pryè.
{108026}{108063}No tak!
{108100}{108142}Musíme zmizet, Clem.
{108143}{108181}Musíme jít.
{108254}{108310}Na to teï není èas!
{108382}{108445}- Proè poøád musíme nìkam utíkat.|- Bude to v poøádku, jenom pojï.
{108454}{108495}Jenom musíme najít|lepší místo, tudy.
{108496}{108533}Ne, tudy.
{108568}{108614}Vùbec mi nepomáháš.
{108703}{108752}Kam mì to vleèeš, Joele?
{109063}{109126}Ráda se na vás dívám,|kdy pracujete.
{109223}{109303}Myslím, e se pùjdu|na chvilku projít.
{109314}{109437}Jestli vám to nebude vadit. Vypadá to,|e tady u je všechno pod kontrolou.
{109469}{109541}Dobøe, to klidnì mùeš.
{109801}{109841}Máte rád citáty, Howarde?
{109892}{109921}Jak to myslíte?
{109921}{109998}Vdy víte, vıroky slavnıch.
{109998}{110053}Nacházím v jejich èetbì inspiraci.
{110054}{110149}Moná by se vám|nìkterı z nich líbil.
{110150}{110185}Urèitì.
{110199}{110241}Rád bych nìjakı slyšel.
{110242}{110283}Znám jeden.
{110284}{110378}"Poehnáni jsou zapomnìtliví,|nebo si berou to lepší i ze svıch omylù."
{110379}{110425}- To byl Nietzsche, e?|- Ano.
{110426}{110484}Myslela jsem, e vám|øeknu nìjakı, co neznáte.
{110485}{110545}To ne, tohle je dobrı citát.
{110546}{110611}- Jsem rád, e ho oba známe.|- Ano.
{110629}{110714}Mám ráda ještì jeden,|kterı je od papee Alexandra.
{110714}{110759}Alexandera Popea?
{110764}{110818}Aha, no jasnì, sakra.
{110822}{110910}Myslela jsem na to,|a neøeknu pape Alexander,
{110911}{110966}e to bude znít hloupì,|a nakonec to øeknu.
{110967}{111036}- Nic se nestalo.|- Jste vánì miláèek.
{111106}{111132}Ten citát zní.
{111133}{111214}"Jak blaenı vestálèin údìl je,
{111228}{111284}na svìt zapomene, a na ni zase svìt.
{111319}{111381}Neposkvrnìné mysli vìènı svit!
{111409}{111457}Motlitby její vyslyšeny,
{111461}{111501}pøání umí se zbıt."
{111501}{111610}Pøála bych si bıt|obrovitánskı slon.
{111626}{111682}S chobotem tak dlouhım,|jako má tenhle.
{111712}{111739}Clem?
{111759}{111783}Clementine?
{111783}{111853}Ten jsem neznal.|Je nádhernı.
{111854}{111921}Myslela jsem,|e by se mohl hodit.
{112035}{112103}Opravdu obdivuji|vaši práci, Howarde.
{112131}{112205}- Nechci bıt tak osobní.|- To je v poøádku.
{112211}{112255}Jsem rád, e to øíkáte.
{112387}{112427}Omlouvám se.
{112515}{112579}U dlouhou dobu vás miluji.
{112647}{112683}Nemìla jsem to øíkat.
{112687}{112760}Mary, ty jsi bájeèné dìvèe.
{112788}{112819}Ale já...
{112820}{112924}Já mám enu a dìti.|Vdy víš, e jsem enatı.
{112931}{112978}Mary.
{113026}{113085}Mary, tohle nesmíme.
{113484}{113532}Dobré ráno, paní Mierzwiaková.
{113765}{113794}- Co se dìje?|- Proboha!
{113795}{113835}Kdo je to?
{114150}{114206}Dìkuji, Stane.|Mnohokrát dìkuji.
{114331}{114383}Hollis! Hollis!
{114402}{114431}Hollis!
{114461}{114510}Poèkej, Hollis.
{114531}{114590}- Vìdìla jsem to, Howarde.|- Nechtìl jsem, aby to tak dopadlo.
{114591}{114682}Pøijel jsem sem pracovat.|Hollis, bylo to jenom chvilkové poblouznìní.
{114683}{114732}Za všechno mùu já.
{114733}{114787}Pøísahám, e jsem|ho to donutila udìlat.
{114823}{114895}Nebuï netvor, Howarde.|Øekni jí to.
{114959}{114999}Co mi má øíct?
{115005}{115051}Ubohé dítì.
{115091}{115133}Je váš.
{115143}{115183}Stejnì jako pøedtím.
{115425}{115455}Coe?
{115703}{115757}Mezi námi u|kdysi nìco bylo.
{115792}{115868}Omlouvám se,|chtìla jsi zákrok.
{115912}{115960}Chtìla jsi s tím skonèit.
{115968}{116049}A takhle jsi to mohla pøekonat.
{116208}{116248}Musím jít.
{116249}{116323}Dokonèit práci.|Je u skoro ráno.
{116369}{116404}Promluvíme si pozdìji.
{116436}{116467}Souhlasíš?
{116897}{116950}Mùu tì hodit domù?
{117228}{117283}- Ahoj.|- Ahoj.
{117321}{117397}Nemyslela jsem si,|e tì ještì nìkdy uvidím.
{117424}{117459}Myslela jsem, e jsi byl...
{117471}{117553}zahanbenı. Utekl jsi.
{117554}{117593}Chtìl jsem tì vidìt.
{117594}{117633}Ano?
{117665}{117794}Rád bych tì|vzal nìkam ven.
{117806}{117842}Jsi enatı.
{117866}{117927}Ještì ne,|ještì nejsem enatı.
{117939}{117978}Ne, nejsem enatı.
{117979}{118080}Øeknu ti to na rovinu,|mám veliké nároky.
{118081}{118216}Nebudu chodit po špièkách okolo toho|tvıho manelství, nebo co to vlastnì je.
{118217}{118289}Pokud chceš bıt se mnou,|musíš bıt jenom se mnou.
{118299}{118325}Dobøe.
{118344}{118486}Spousta chlapù si myslí, e jsem to, co jim|v ivotì chybí, e jenom se mnou jsou naivu.
{118496}{118579}Já jsem ale jenom vyèùraná holka,|co si hledá svùj kousek svìta.
{118585}{118627}Tak mi nevnucuj ten svùj.
{118628}{118676}Tuhle øeè si|opravdu dobøe pamatuji.
{118695}{118738}Obtoèila jsem si tì|kolem prstu, co?
{118739}{118796}Obtoèila sis|kolem nìj celı svìt.
{118796}{118836}Asi jo.
{118884}{118938}Poøád si myslím,|e mì mùeš zachránit.
{118945}{118988}I po tom všem.
{119028}{119064}Já vím.
{119120}{119158}Bude to jiné.
{119204}{119272}Jenom nám musíš dát|ještì jednu šanci.
{119355}{119404}Pamatuj si mì.
{119415}{119463}Sna se ze všech sil.
{119524}{119571}A moná tu šanci mít budeme.
{120316}{120441}Dobøe, nejprve mi øekni vše, co si|pamatuješ, a potom budeme pokraèovat.
{120445}{120474}Dobøe.
{120506}{120561}Zamilovala jsem se|do tebe na první pohled.
{120573}{120629}Nesnail ses mì sbalit.
{120634}{120673}To se mi líbilo.
{120718}{120782}Ze zaèátku jsem|byla hroznì nervózní.
{120783}{120834}Chtìla jsem, aby sis|o mnì myslel, e jsem chytrá.
{120877}{120932}Tìšila jsem se do práce.
{120933}{121054}Poøád jsem si pøedstavovala,|e jsme svoji a máme spolu dìti.
{121074}{121098}Prostì...
{121100}{121152}Ach, Howie, tohle nedokáu.
{121166}{121230}Shodli jsme se,|e to tak bude nejlepší, Mary.
{121231}{121270}Já vím.
{121300}{121334}Proboha.
{121340}{121391}- Vezmu to.|- Ne.
{121397}{121438}Mám to vzít?
{121454}{121522}- Mùeš vzít lednièku.|- Zrovna lednièku.
{121526}{121578}Máš to?|Tohle vezmu já.
{121618}{121658}- Radši nic neber!|- Mùu vzít tohle.
{121658}{121729}To nech bıt,|mùeš zavøít kufr.
{121807}{121851}Dnes jsme se poprvé potkali.
{121859}{121947}Byla jsi dole a u moøe,|skoro tì v té dálce nebylo vidìt.
{121948}{122003}Pamatuju si, e pøesto jsi|mì nìèím hroznì pøitahovala.
{122015}{122096}Pomyslel jsem si: "Páni, to je zvláštní,|pøitahují mì nìèí záda."
{122125}{122166}Mìla jsi na sobì|tu oranovou bundu.
{122166}{122216}Kterou jsem tak rád poznal.
{122217}{122266}A nakonec ji snad i nenávidìl.
{122268}{122365}Pøipadalo mi,|e je to fakt super bunda.
{122366}{122400}Ahoj.
{122448}{122478}Ahoj.
{122479}{122512}Vidìla jsem tì.
{122512}{122552}Jak tu sedíš.
{122553}{122584}Sám.
{122600}{122630}A øekla jsem si.
{122636}{122753}Díky Bohu, e je tu ještì nìkdo normální,|kdo taky neví, jak ovládat tyhle vìci.
{122753}{122785}To jo.
{122790}{122863}Nevím, co ti na to øíct.
{122869}{122913}Já jsem Clementine.
{122934}{123018}Mùu si vzít kousek|z tvıho kuøete?
{123027}{123065}U sis ho vzala.
{123066}{123121}Bez toho, e bys|poèkala na odpovìï.
{123219}{123257}To bylo tak intimní.
{123270}{123321}Jako bychom u spolu chodili.
{123370}{123402}Jmenuji se Joel.
{123421}{123455}Ahoj, Joele.
{123471}{123525}Ne, e budeš vtipkovat|o mém jménì.
{123549}{123577}Máš na mysli...
{123578}{123650}"Oh my darling, oh my darling,|oh my darling Clementine..."
{123661}{123707}Huckleberry Hound, je to tak?
{123723}{123771}Jo, tak nìco.
{123772}{123818}Ale ne, ádné vtipy.
{123826}{123918}Kdy jsem byl malı, tak moje nejoblíbenìjší|hraèka byla postavièka Huckleberry Hounda.
{124008}{124061}Myslím, e|tvé jméno je kouzelné.
{124134}{124166}Jsme tu, Joele.
{124194}{124246}Za chvilku bude po všem.
{124299}{124326}Já vím.
{124351}{124382}Co budeme dìlat?
{124458}{124505}Vychutnáme si to.
{124911}{124958}- Jsi enatı?|- Ne.
{124959}{125016}Tak se spolu nastìhujeme sem!
{125017}{125048}U s nìkım...
{125048}{125091}tak trochu iju.
{125092}{125131}Je to mu nebo ena?
{125132}{125228}Coe?|ena. ena to je.
{125277}{125345}Aspoò zase nebuším|na špatnı dveøe.
{125427}{125468}Ty znáš lidi, co tu bydlí?
{125469}{125519}Samozøejmì, e ne. Pojï.
{125564}{125608}Co kdy mají psa?
{125612}{125651}Nemají psa.
{125687}{125724}Co to dìláš?
{125734}{125776}Venku mrzne.
{125788}{125821}To snad není moné.
{125892}{125941}- Clementine!|- Pojï za mnou.
{126124}{126156}Raète dál, pane.
{126157}{126202}Vzduch je èistı.
{126219}{126311}Nikdo sem dnes|v noci nepøijde, vìø mi.
{126349}{126388}Je tu tma.
{126392}{126433}Take...
{126434}{126498}Jak se ta|tvoje dívka jmenuje?
{126511}{126567}Naomi.|My ale spolu nejsme.
{126576}{126629}- Nejsme.|- Co?
{126632}{126693}Tohle je skvìlı,|mrknu se, kde tu mají...
{126701}{126822}- svíèky, zápalky a nìjakou lahvinku.|- Proboha.
{126990}{127054}- Mìli bychom u jít.|- Telefon není zapojenı.
{127070}{127113}- Coe?|- Mìli bychom jít.
{127114}{127170}Proè?|Teï je to náš dùm.
{127174}{127239}Protoe dnes veèer jsme
{127240}{127298}David a Ruth Laskinovi.
{127306}{127345}Koho si bereš ty?
{127358}{127401}Byla bych radši Ruth, ale...
{127408}{127455}pøizpùsobím se.
{127574}{127612}Alkohol!
{127612}{127642}Take...
{127642}{127711}- Vyhovuje ti víno?|- Já nevím.
{127719}{127874}Ty zatím vyber víno, já jdu najít lonici|a nìco pohodlnìjšího na sebe.
{127935}{127992}- Právì teï jsem bezcitná.|- Mìli bychom jít.
{128060}{128114}Tohle si pamatuju.
{128157}{128199}Tak si bì!
{128227}{128253}Odešel jsem.
{128280}{128335}Myslel jsem si,|e jsi moná blázen.
{128345}{128380}Tolik vzrušení.
{128439}{128482}Chtìla bych, abys zùstal.
{128483}{128515}To bych si pøál taky.
{128516}{128553}Teï bych si to pøál.
{128554}{128602}Pøál bych si udìlat|spoustu vìci.
{128655}{128820}Pøál bych si, abych zùstal.
{128834}{128860}Opravdu.
{128860}{128953}- Kdy jsem se vrátila dolù, byl jsi u pryè.|- Šel jsem ven.
{128968}{129061}- Proè?|- Nevím, bál jsem se jak malı kluk.
{129080}{129124}Byl jsem úplnì mimo, nevím.
{129125}{129184}- Bál ses?|- Ano.
{129233}{129286}Myslel jsem, e jsi to vìdìla.
{129309}{129400}Asi jsem se snail|zmenšit svoje zahanbení.
{129423}{129464}Nìco jsem ti øekla?
{129472}{129498}Ano.
{129559}{129598}Øekla jsi mi: "Tak si bì!"
{129616}{129668}S takovım opovrením.
{129669}{129717}To je mi líto.
{129717}{129745}Nic se nestalo.
{129881}{129905}Joelie?
{129937}{129982}A co kdybys tentokrát zùstal?
{130054}{130099}Odešel jsem ven.
{130125}{130161}U mi nezùstala|ádná vzpomínka.
{130162}{130225}Tak se pojï|aspoò rozlouèit.
{130247}{130289}Aspoò pøedstírej,|e ještì nìjakou máš.
{130562}{130601}Sbohem, Joele.
{130618}{130658}Miluji tì.
{130668}{130749}Potkáme se v Montauku.
{130866}{130972}To letadlo havarovalo.|Ne, e jsem s ním já havaroval.
{131115}{131195}Jsi zkouøenı a ještì øídíš.
{131196}{131284}Jo, ale jenom proto, e jsem opilı.|A tráva mi vyvauje ten alkohol.
{131322}{131432}To je vìdeckı dokázané.
{131433}{131482}Lásko,|radši se dívej na cestu.
{131557}{131628}Vidìla jsem tì,|jak se bavíš s nìjakou dívkou.
{131633}{131702}- Byla milá.|- Kdo to byl?
{131756}{131793}Byla to...
{131809}{131845}jenom nìjaká dívka.
{132020}{132051}Hotovo.
{132933}{132998}Odvezu dodávku.
{133002}{133042}Díky, Stane.
{133053}{133091}Promluvíme si.
{134998}{135027}Ahoj!
{135083}{135111}Ahoj.
{135154}{135191}- Vzala sis svoje vìci.|- Správnì.
{135192}{135237}U se nevrátíš?
{135262}{135336}- Chtìl bych, aby ses vrátila.|- Vìdìl jsi o tom?
{135337}{135381}Pøísahám, e ne.
{135394}{135439}Take mazaní jsi neprovádìl ty?
{135440}{135469}Samozøejmì, e ne.
{135469}{135540}A nikdy jsi nemìl ani podezøení,|e jsem s ním nìco mìla?
{135560}{135600}Moná jednou.
{135641}{135766}Šel jsem z práce. Byla jsi s ním|u auta a bavili jste se spolu.
{135780}{135844}Tak jsem na tebe|èekal a ty ses smála.
{135865}{135902}Jak jsem vypadala?
{135959}{135997}Vypadala jsi šastná.
{135999}{136080}Šastná a e máš tajemství.
{136098}{136128}A potom?
{136129}{136209}U jsem vás tak|nikdy nevidìl, take...
{136214}{136284}Myslel jsem si,|e se mi jenom nìco zdálo.
{136910}{136969}Mám tì opravdu rád,|Mary Svevo.
{136985}{137021}Víš to?
{137285}{137317}Díky.
{138158}{138206}Skoèím si|pro kartáèek na zuby.
{138560}{138608}Kde jsi, Clem?
{138629}{138717}Proè se na mì zlobíš?|Nechápu, co jsem udìlal.
{138752}{138838}Co jsem ti udìlal?|Moc tì miluju.
{138842}{138893}Udìlám cokoli,|aby ses cítila šastná.
{138896}{138949}Jenom mi øekni co,|a já to udìlám.
{138990}{139056}Ráno se zastavím,|abych se ujistil, e jsi v poøádku.
{139375}{139425}Zvedejte kotvy, pane.
{139449}{139507}To vèera bylo vánì milé.
{139537}{139562}Milé?
{139567}{139657}Kurva, byla to ta nejlepší noc|mıho zkurvenıho ivota.
{139658}{139729}- Lepší?|- To teda je.
{139829}{139849}To je divnı.
{139850}{139919}Pro staré pacienty|doktora Howarda Mierzwiaka:
{139920}{139993}Jmenuji se Mary Svevo.|Známe se, ale nepamatujete si mì.
{139994}{140113}Pracuji pro firmu, kterou jste si najali,|aby vám vymazala èást vaší pamìti.
{140114}{140189}- Rozhodla jsem se...|- Je tam ještì nìco jiného?
{140190}{140282}Abych to napravila, poslala jsem|kadému záznamy o jeho zákroku.
{140318}{140377}Jmenuji se|Clementine Kruczynski
{140388}{140453}a chci si nechat vymazat|z pamìti Joela Barishe.
{140462}{140487}Co to má bıt?
{140488}{140516}Nevím.
{140517}{140615}Je nudnı a to snad staèí jako dùvod,|nechat si nìkoho vymazat.
{140623}{140718}Pøemıšlela jsem, jaká jsem byla pøedtím|a jaká jsem teï, a zjistila jsem, e mì zmìnil.
{140719}{140769}Mám pocit, e jsem|teï poøád naštvaná.
{140769}{140847}U se nemám ráda.
{140848}{140906}Nemùu se na nìho|u ani podívat.
{140907}{140970}Ten jeho patetickı,|slabošskı, omluvnı usmìv,
{140971}{141020}pøi kterém vypadá jak|nìjakı podìlanı štìòátko.
{141020}{141082}- Proè to dìláš?|- Já nic nedìlám.
{141098}{141166}- To má bıt nìjakı vtip?|- Ne!
{141178}{141234}- Je to vtip.|- Joele, není to vtip.
{141235}{141350}- Jasnì, e je!|- Dobøe, tak na chvilku zastavme...
{142043}{142115}Vypadni odsud!
{142138}{142199}- Mùeme si promluvit?|- Ne, vypadni!
{142989}{143025}Joel Barish.
{143040}{143082}Ahoj, Clementine.
{143083}{143109}Ahoj.
{143110}{143150}Rád tì vidím.
{143257}{143303}Nemá vzdìlání.
{143304}{143390}Moná je chytrá,|ale vùbec nemá vzdìlání.
{143403}{143462}O kníkách s ní|vùbec nemùu mluvit.
{143462}{143518}Ona radìji ète|èasopisy pro eny.
{143547}{143615}Mìla by si radši|pøeèíst slovník.
{143630}{143692}Bylo mi trapnì, kdy|jsme spolu byli mezi lidmi.
{143699}{143727}Ahoj.
{143783}{143808}Ahoj.
{143910}{143942}Podívej se, co jsem našel.
{143943}{144032}Clementine je fakt|skvìlá svùdnice.
{144042}{144126}Její chování vám dává nadìji,|e s ní to bude jiné.
{144174}{144258}Jsem tu celkem hubená.
{144535}{144593}Omlouvám se,|e jsem na tebe køièel.
{144623}{144656}To je v poøádku.
{144767}{144848}Joele, vánì se mi líbíš. Je mi líto,|e jsem o tobì øíkala takové vìci.
{144849}{144891}Vypnu to, ano?
{144892}{144945}Nech to puštìné, tak je to fér.
{144989}{145078}Co to má poøád|s tìmi vlasy?
{145078}{145118}Vdy jsou hrozné.
{145119}{145161}Opravdu se mi líbí|tvoje vlasy.
{145175}{145219}- Vánì se mi líbí.|- Díky.
{145325}{145371}Dáš si nìco k pití?
{145372}{145416}Máš Whiskey?
{145434}{145512}U mi vùbec nepøipadá sexy.
{145543}{145732}Poslední noc, co jsme se vidìli,|u vùbec nevypadala sexy, byla spíš k pláèi.
{145757}{145810}Promiò, myslel jsem,|e mám víc.
{145810}{145928}Kdy chce, aby ji lidi|mìli rádi, tak se s nimi vyspí.
{145960}{146051}Vyuije kadé pøíleitosti|si s nìkım zašoustat.
{146056}{146238}Je tak ubohá, e za chvilku u|nebude nikdo, s kım by to ještì nedìlala.
{146239}{146329}- Tohle já nedìlám.|- Já si to o tobì nemyslím.
{146330}{146384}- Protoe já taková nejsem.|- Vím.
{146392}{146452}Tohle mì vánì ranilo,|protoe tohle nedìlám.
{146452}{146518}- Omlouvám se.|- Já se omlouvám.
{146543}{146670}Byla jsem zmatená,|asi bych tu nemìla bıt.
{146825}{146873}- Sbohem.|- Sbohem.
{146918}{146962}Ráda jsem tì poznala.
{147042}{147202}Je hrozné, e strávíte tolik èasu s nìkım,|o kom nakonec zjistíte, e ho vùbec neznáte.
{147306}{147330}Poèkej!
{147401}{147427}- Co je?|- Nevím.
{147428}{147481}- Co po mnì chceš, Joele?|- Jenom se na chvilièku zastav.
{147482}{147519}Já nevím.|Jenom se na chvilièku zastav.
{147525}{147586}Na chvilku.
{147921}{147975}- Dobøe.|- Opravdu?
{147985}{148020}Nevím, jak se má ít, Joele.
{148021}{148083}Jsem jenom vyèùraná holka,|co si hledá svùj kousek svìta.
{148084}{148119}Nejsem dokonalá.
{148120}{148177}Právì teï není nic,|co by mi na tobì vadilo.
{148178}{148243}Ale jednou ti na mnì|bude nìco vadit.
{148248}{148291}A budeš si o mnì|myslet takovı vìci.
{148292}{148385}Ty mì zase zaèneš nudit a budu se|cítit jako v pasti, protoe taková jsem já.
{148428}{148465}Dobøe.
{148561}{148601}Dobøe.
{148704}{148757}Dobøe.

